-- =====================================================================
--  BuildSizes - CONFIG   (edite, salve, e aperte F7 dentro do jogo)
--
--  COMO USAR
--    1. Ache a estrutura na lista e troque  ativo = false  por  ativo = true
--    2. Escolha o  tamanho :  1.0 = normal | 0.65 = menor | 0.3 = bem pequeno
--                             1.5 = maior  (da pra AUMENTAR tambem)
--    3. Salve este arquivo e aperte  F7  dentro do jogo
--    4. No modo de construcao, mire com o fantasma pousado no chao. Depois
--       RE-SELECIONE a estrutura no menu -- ela nasce no tamanho novo.
--
--  A escala e PROPORCIONAL: tamanho, posicao das pecas e a area que ela ocupa
--  encolhem juntos. Por isso da pra empilhar/aproximar sem colisao esquisita.
--
--  Vale para o que voce construir DEPOIS. O que ja esta no chao nao muda.
--
--  As 3 marcadas [MiniBuilds] ja sao tratadas por outro mod -- deixe false,
--  senao a escala e aplicada duas vezes.
-- =====================================================================
return {

    -- ---------- PRODUCAO (45) ----------
    { nome = "Bancada Primitiva",               classe = "BP_BuildObject_WorkBench_C",             ativo = true,  tamanho = 0.65 },  -- <== EXEMPLO LIGADO
    { nome = "Bancada de Conserto",             classe = "BP_BuildObject_RepairBench_C",           ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Equipamentos de Pal",  classe = "BP_BuildObject_WorkBench_SkillUnlock_C", ativo = false, tamanho = 1.0 },
    { nome = "Bancada de Alta Qualidade",       classe = "BP_BuildObject_Factory_Hard_01_C",       ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Linha",                classe = "BP_BuildObject_Factory_Hard_02_C",       ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Linha II",             classe = "BP_BuildObject_Factory_Hard_03_C",       ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Civilização Avançada", classe = "BP_BuildObject_Factory_Hard_4_C",        ativo = false, tamanho = 1.0 },
    { nome = "Bancada da Civilização Antiga",   classe = "BP_BuildObject_AncientWorkBench_C",      ativo = false, tamanho = 1.0 },
    { nome = "Mesa de Projetos",                classe = "BP_BuildObject_CompositeDesk_C",         ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Dinheiro",             classe = "BP_BuildObject_Factory_Money_C",         ativo = false, tamanho = 1.0 },
    { nome = "Conversor de Relíquias Antigas",  classe = "BP_BuildObject_AncientRelicRecycler_C",  ativo = false, tamanho = 1.0 },
    { nome = "Oficina de Esferas",              classe = "BP_BuildObject_SphereFactory_Black_01_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Linha de Esferas",     classe = "BP_BuildObject_SphereFactory_Black_02_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Linha de Esferas II",  classe = "BP_BuildObject_SphereFactory_Black_03_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Esferas de Civilização Avançada", classe = "BP_BuildObject_SphereFactory_Black_04_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Armas",                classe = "BP_BuildObject_WeaponFactory_Dirty_01_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Linha de Armas",       classe = "BP_BuildObject_WeaponFactory_Dirty_02_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Linha de Armas II",    classe = "BP_BuildObject_WeaponFactory_Dirty_03_C", ativo = false, tamanho = 1.0 },
    { nome = "Fábrica de Armas de Civilização Avançada", classe = "BP_BuildObject_WeaponFactory_Dirty_4_C", ativo = false, tamanho = 1.0 },
    { nome = "Madeireira",                      classe = "BP_BuildObject_StationDeforest2_C",      ativo = false, tamanho = 1.0 },
    { nome = "Madeireira II",                   classe = "BP_BuildObject_StationDeforest3_C",      ativo = false, tamanho = 1.0 },
    { nome = "Pedreira",                        classe = "BP_BuildObject_StonePit_C",              ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Metais",               classe = "BP_BuildObject_CopperPit_C",             ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Metais II",            classe = "BP_BuildObject_CopperPit_2_C",           ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Carvão",               classe = "BP_BuildObject_CoalPit_C",               ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Enxofre",              classe = "BP_BuildObject_SulfurPit_C",             ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Quartzo Puro",         classe = "BP_BuildObject_QuartzPit_C",             ativo = false, tamanho = 1.0 },
    { nome = "Extrator de Petróleo",            classe = "BP_BuildObject_OilPump_C",               ativo = false, tamanho = 1.0 },
    { nome = "Extrator de Petróleo de Alta Pressão", classe = "BP_BuildObject_OilPump02_C",             ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Exoquartzo",           classe = "BP_BuildObject_CrystalPit_C",            ativo = false, tamanho = 1.0 },
    { nome = "Garimpo de Soralite",             classe = "BP_BuildObject_SkyIslandOrePit_C",       ativo = false, tamanho = 1.0 },
    { nome = "Gerador de Materiais da Civilização Antiga", classe = "BP_BuildObject_AncientMultiProduct_C",   ativo = false, tamanho = 1.0 },
    { nome = "Forno Primitivo",                 classe = "BP_BuildObject_BlastFurnace_C",          ativo = false, tamanho = 1.0 },
    { nome = "Forno Melhorado",                 classe = "BP_BuildObject_BlastFurnace_2_C",        ativo = false, tamanho = 1.0 },
    { nome = "Forno Elétrico",                  classe = "BP_BuildObject_BlastFurnace3_C",         ativo = false, tamanho = 1.0 },
    { nome = "Forno Gigantesco",                classe = "BP_BuildObject_BlastFurnace4_C",         ativo = false, tamanho = 1.0 },
    { nome = "Forno da Civilização Antiga",     classe = "BP_BuildObject_AncientBlastFurnace_C",   ativo = false, tamanho = 1.0 },
    { nome = "Moenda",                          classe = "BP_BuildObject_FlourMill_C",             ativo = false, tamanho = 1.0 },
    { nome = "Triturador",                      classe = "BP_BuildObject_Crusher_C",               ativo = false, tamanho = 1.0 },
    { nome = "Triturador de Gelo",              classe = "BP_BuildObject_IceCrusher_C",            ativo = false, tamanho = 1.0 },
    { nome = "Boticário Medieval",              classe = "BP_BuildObject_MedicineFacility_01_C",   ativo = false, tamanho = 1.0 },
    { nome = "Produção de Remédios Elétrica",   classe = "BP_BuildObject_MedicineFacility_02_C",   ativo = false, tamanho = 1.0 },
    { nome = "Produção de Remédios de Civilização Avançada", classe = "BP_BuildObject_MedicineFacility_03_C",   ativo = false, tamanho = 1.0 },
    { nome = "Tanque de Pesca",                 classe = "BP_BuildObject_FishingPond01_C",         ativo = false, tamanho = 1.0 },
    { nome = "Grande Tanque de Pesca",          classe = "BP_BuildObject_FishingPond02_C",         ativo = false, tamanho = 1.0 },

    -- ---------- ESTRUTURA (134) ----------
    { nome = "Fundação de Madeira",             classe = "BP_BuildObject_Wood_Foundation_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular de Madeira",  classe = "BP_BuildObject_Wood_TriangleFoundation_C",              ativo = false, tamanho = 1.0 },
    { nome = "Muro de Madeira",                 classe = "BP_BuildObject_Wood_Wall_V2_C",                         ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela de Madeira",    classe = "BP_BuildObject_Wood_WindowWall_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Porta de Madeira",                classe = "BP_BuildObject_Wood_DoorWall_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal de Madeira",      classe = "BP_BuildObject_Wood_DiagonalWall_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Madeira",    classe = "BP_BuildObject_Wood_TriangleWall_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Madeira (Invertida)", classe = "BP_BuildObject_Wood_TriangleWallReverse_C",             ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Madeira",              classe = "BP_BuildObject_Wood_Roof_C",                            ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular de Madeira",   classe = "BP_BuildObject_Wood_TriangleRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado de Madeira",    classe = "BP_BuildObject_Wood_SlantedRoof_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Madeira", classe = "BP_BuildObject_Wood_SlopedRoofCorner_C",                ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Madeira (Invertido)", classe = "BP_BuildObject_Wood_SlopedRoofCornerReverse_C",         ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina de Madeira",     classe = "BP_BuildObject_Wood_TriangleStairsCorner_C",            ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide de Madeira",  classe = "BP_BuildObject_Wood_PyramidRoof_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Escada de Madeira",               classe = "BP_BuildObject_Wood_Stair_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals de Madeira",   classe = "BP_BuildObject_Wood_WallGate_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Cerca de Madeira",                classe = "BP_BuildObject_Wood_Fence_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Escada",                          classe = "BP_BuildObject_Wood_Ladder_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Fundação de Pedra",               classe = "BP_BuildObject_Stone_Foundation_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular de Pedra",    classe = "BP_BuildObject_Stone_TriangleFoundation_C",             ativo = false, tamanho = 1.0 },
    { nome = "Muro de Pedra",                   classe = "BP_BuildObject_Stone_Wall_V2_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela de Pedra",      classe = "BP_BuildObject_Stone_WindowWall_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Porta de Pedra",                  classe = "BP_BuildObject_Stone_DoorWall_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal de Pedra",        classe = "BP_BuildObject_Stone_DiagonalWall_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Pedra",      classe = "BP_BuildObject_Stone_TriangleWall_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Pedra (Invertida)", classe = "BP_BuildObject_Stone_TriangleWallReverse_C",            ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pedra",                classe = "BP_BuildObject_Stone_Roof_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular de Pedra",     classe = "BP_BuildObject_Stone_TriangleRoof_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado de Pedra",      classe = "BP_BuildObject_Stone_SlantedRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Pedra", classe = "BP_BuildObject_Stone_SlopedRoofCorner_C",               ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Pedra (Invertido)", classe = "BP_BuildObject_Stone_SlopedRoofCornerReverse_C",        ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina de Pedra",       classe = "BP_BuildObject_Stone_TriangleStairsCorner_C",           ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide de Pedra",    classe = "BP_BuildObject_Stone_PyramidRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Escada de Pedra",                 classe = "BP_BuildObject_Stone_Stair_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals de Pedra",     classe = "BP_BuildObject_Stone_WallGate_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Cerca de Pedra",                  classe = "BP_BuildObject_Stone_Fence_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Fundação de Metal",               classe = "BP_BuildObject_Metal_Foundation_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular de Metal",    classe = "BP_BuildObject_Iron_TriangleFoundation_C",              ativo = false, tamanho = 1.0 },
    { nome = "Muro de Metal",                   classe = "BP_BuildObject_Metal_Wall_V2_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela de Metal",      classe = "BP_BuildObject_Metal_WindowWall_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Porta de Metal",                  classe = "BP_BuildObject_Metal_DoorWall_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal de Metal",        classe = "BP_BuildObject_Iron_DiagonalWall_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Metal",      classe = "BP_BuildObject_Metal_TriangleWall_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Metal (Invertida)", classe = "BP_BuildObject_Iron_TriangleWallReverse_C",             ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Metal",                classe = "BP_BuildObject_Metal_Roof_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular de Metal",     classe = "BP_BuildObject_Iron_TriangleRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado de Metal",      classe = "BP_BuildObject_Metal_SlantedRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Metal", classe = "BP_BuildObject_Iron_SlopedRoofCorner_C",                ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Metal (Invertido)", classe = "BP_BuildObject_Iron_SlopedRoofCornerReverse_C",         ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina de Metal",       classe = "BP_BuildObject_Iron_TriangleStairsCorner_C",            ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide de Metal",    classe = "BP_BuildObject_Iron_PyramidRoof_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Escada de Metal",                 classe = "BP_BuildObject_Metal_Stair_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals de Metal",     classe = "BP_BuildObject_Iron_WallGate_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Cerca de Metal",                  classe = "BP_BuildObject_Iron_Fence_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Fundação de Vidro",               classe = "BP_BuildObject_Glass_Foundation_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular de Vidro",    classe = "BP_BuildObject_Glass_TriangleFoundation_C",             ativo = false, tamanho = 1.0 },
    { nome = "Parede de Vidro",                 classe = "BP_BuildObject_Glass_Wall_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela de Vidro",      classe = "BP_BuildObject_Glass_WindowWall_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Parede com Porta de Vidro",       classe = "BP_BuildObject_Glass_DoorWall_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal de Vidro",        classe = "BP_BuildObject_Glass_DiagonalWall_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Vidro",      classe = "BP_BuildObject_Glass_TriangleWall_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular de Vidro (Invertida)", classe = "BP_BuildObject_Glass_TriangleWallReverse_C",            ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Vidro",                classe = "BP_BuildObject_Glass_Roof_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular de Vidro",     classe = "BP_BuildObject_Glass_TriangleRoof_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado de Vidro",      classe = "BP_BuildObject_Glass_SlantedRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Vidro", classe = "BP_BuildObject_Glass_SlopedRoofCorner_C",               ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular de Vidro (Invertido)", classe = "BP_BuildObject_Glass_SlopedRoofCornerReverse_C",        ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina de Vidro",       classe = "BP_BuildObject_Glass_TriangleStairsCorner_C",           ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide de Vidro",    classe = "BP_BuildObject_Glass_PyramidRoof_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Escada de Vidro",                 classe = "BP_BuildObject_Glass_Stair_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals de Vidro",     classe = "BP_BuildObject_Glass_WallGate_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Cerca de Vidro",                  classe = "BP_BuildObject_Glass_Fence_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Fundação Japonesa",               classe = "BP_BuildObject_JapaneseStyle_foundation_C",             ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular Japonesa",    classe = "BP_BuildObject_JapaneseStyle_TriangleFoundation_C",     ativo = false, tamanho = 1.0 },
    { nome = "Parede Japonesa",                 classe = "BP_BuildObject_JapaneseStyle_Wall_01_C",                ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela Japonesa",      classe = "BP_BuildObject_JapaneseStyle_WindowWall_C",             ativo = false, tamanho = 1.0 },
    { nome = "Parede com Porta Japonesa A",     classe = "BP_BuildObject_JapaneseStyle_DoorWall_01_C",            ativo = false, tamanho = 1.0 },
    { nome = "Parede com Porta Japonesa B",     classe = "BP_BuildObject_JapaneseStyle_DoorWall_02_C",            ativo = false, tamanho = 1.0 },
    { nome = "Parede com Porta Japonesa C",     classe = "BP_BuildObject_JapaneseStyle_DoorWall_03_C",            ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal Japonesa",        classe = "BP_BuildObject_JapaneseStyle_DiagonalWall_C",           ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular Japonesa",      classe = "BP_BuildObject_JapaneseStyle_TriangleWall_C",           ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular Japonesa (Invertida)", classe = "BP_BuildObject_JapaneseStyle_TriangleWallReverse_C",    ativo = false, tamanho = 1.0 },
    { nome = "Telhado Japonês A",               classe = "BP_BuildObject_JapaneseStyle_roof_01_C",                ativo = false, tamanho = 1.0 },
    { nome = "Telhado Japonês B",               classe = "BP_BuildObject_JapaneseStyle_roof_02_C",                ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular Japonês A",    classe = "BP_BuildObject_JapaneseStyle_TriangleRoof_01_C",        ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular Japonês B",    classe = "BP_BuildObject_JapaneseStyle_TriangleRoof_02_C",        ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Japonês",       classe = "BP_BuildObject_JapaneseStyle_SlantedRoof_C",            ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular Japonês", classe = "BP_BuildObject_JapaneseStyle_SlopedRoofCorner_C",       ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular Japonês (Invertido)", classe = "BP_BuildObject_JapaneseStyle_SlopedRoofCornerReverse_C", ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina Japonês",        classe = "BP_BuildObject_JapaneseStyle_TriangleStairsCorner_01_C", ativo = false, tamanho = 1.0 },
    { nome = "pt-BR_Text",                      classe = "BP_BuildObject_JapaneseStyle_TriangleStairsCorner_02_C", ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide Japonês",     classe = "BP_BuildObject_JapaneseStyle_PyramidRoof_C",            ativo = false, tamanho = 1.0 },
    { nome = "Escada Japonesa",                 classe = "BP_BuildObject_JapaneseStyle_stair_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Pilar Japonês",                   classe = "BP_BuildObject_JapaneseStyle_Pillar_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals Japonesa",     classe = "BP_BuildObject_JapaneseStyle_WallGate_C",               ativo = false, tamanho = 1.0 },
    { nome = "Cerca Japonesa",                  classe = "BP_BuildObject_JapaneseStyle_Fence_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Fundação Despojada",              classe = "BP_BuildObject_SF_Foundation_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular Despojada",   classe = "BP_BuildObject_SF_TriangleFoundation_C",                ativo = false, tamanho = 1.0 },
    { nome = "Parede Despojada",                classe = "BP_BuildObject_SF_Wall_C",                              ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela Despojada",     classe = "BP_BuildObject_SF_WindowWall_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Parede com Porta Despojada",      classe = "BP_BuildObject_SF_DoorWall_02_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal Despojada",       classe = "BP_BuildObject_SF_DiagonalWall_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular Despojada",     classe = "BP_BuildObject_SF_TriangleWall_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular Despojada (Invertida)", classe = "BP_BuildObject_SF_TriangleWallReverse_C",               ativo = false, tamanho = 1.0 },
    { nome = "Telhado Despojado",               classe = "BP_BuildObject_SF_Roof_C",                              ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular Despojado",    classe = "BP_BuildObject_SF_TriangleRoof_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Despojado",     classe = "BP_BuildObject_SF_SlantedRoof_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular Despojado", classe = "BP_BuildObject_SF_SlopedRoofCorner_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular Despojado (Invertido)", classe = "BP_BuildObject_SF_SlopedRoofCornerReverse_C",           ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina Despojado",      classe = "BP_BuildObject_SF_TriangleStairsCorner_C",              ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide Despojado",   classe = "BP_BuildObject_SF_PyramidRoof_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Escada Despojada",                classe = "BP_BuildObject_SF_Stair_C",                             ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals Despojada",    classe = "BP_BuildObject_SF_WallGate_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Cerca Despojada",                 classe = "BP_BuildObject_SF_Fence_C",                             ativo = false, tamanho = 1.0 },
    { nome = "Fundação da Civilização Antiga",  classe = "BP_BuildObject_Ancient_Foundation_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Fundação Triangular da Civilização Antiga", classe = "BP_BuildObject_Ancient_TriangleFoundation_C",           ativo = false, tamanho = 1.0 },
    { nome = "Parede da Civilização Antiga",    classe = "BP_BuildObject_Ancient_Wall_C",                         ativo = false, tamanho = 1.0 },
    { nome = "Parede com Janela da Civilização Antiga", classe = "BP_BuildObject_Ancient_WindowWall_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Parede com Porta da Civilização Antiga", classe = "BP_BuildObject_Ancient_DoorWall_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Parede Diagonal da Civilização Antiga", classe = "BP_BuildObject_Ancient_DiagonalWall_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular da Civilização Antiga", classe = "BP_BuildObject_Ancient_TriangleWall_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Parede Triangular da Civilização Antiga (Invertida)", classe = "BP_BuildObject_Ancient_TriangleWallReverse_C",          ativo = false, tamanho = 1.0 },
    { nome = "Telhado da Civilização Antiga",   classe = "BP_BuildObject_Ancient_Roof_C",                         ativo = false, tamanho = 1.0 },
    { nome = "Telhado Triangular da Civilização Antiga", classe = "BP_BuildObject_Ancient_TriangleRoof_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado da Civilização Antiga", classe = "BP_BuildObject_Ancient_SlantedRoof_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular da Civilização Antiga", classe = "BP_BuildObject_Ancient_SlopedRoofCorner_C",             ativo = false, tamanho = 1.0 },
    { nome = "Telhado Inclinado Triangular da Civilização Antiga (Invertido)", classe = "BP_BuildObject_Ancient_SlopedRoofCornerReverse_C",      ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Quina da Civilização Antiga", classe = "BP_BuildObject_Ancient_TriangleStairsCorner_C",         ativo = false, tamanho = 1.0 },
    { nome = "Telhado de Pirâmide da Civilização Antiga", classe = "BP_BuildObject_Ancient_PyramidRoof_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Escada da Civilização Antiga",    classe = "BP_BuildObject_Ancient_Stair_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Pilar da Civilização Antiga",     classe = "BP_BuildObject_Ancient_Pillar_C",                       ativo = false, tamanho = 1.0 },
    { nome = "Passagem para Pals da Civilização Antiga", classe = "BP_BuildObject_Ancient_WallGate_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Cerca da Civilização Antiga",     classe = "BP_BuildObject_Ancient_Fence_C",                        ativo = false, tamanho = 1.0 },

    -- ---------- ARMAZENAMENTO (30) ----------
    { nome = "Baú de Madeira",                  classe = "BP_BuildObject_ItemChest_C",            ativo = false, tamanho = 1.0 },
    { nome = "Baú de Metal",                    classe = "BP_BuildObject_ItemChest_02_C",         ativo = false, tamanho = 1.0 },
    { nome = "Baú de Metal Refinado",           classe = "BP_BuildObject_ItemChest_03_C",         ativo = false, tamanho = 1.0 },
    { nome = "Caixa Térmica",                   classe = "BP_BuildObject_CoolerBox_C",            ativo = false, tamanho = 1.0 },
    { nome = "Refrigerador",                    classe = "BP_BuildObject_Refrigerator_C",         ativo = false, tamanho = 1.0 },
    { nome = "Baú de Guilda",                   classe = "BP_BuildObject_GuildChest_C",           ativo = false, tamanho = 1.0 },
    { nome = "Distribuidor de Itens",           classe = "BP_BuildObject_BaseCampItemDispenser_C", ativo = false, tamanho = 1.0 },
    { nome = "Baú de Civilização Avançada",     classe = "BP_BuildObject_ItemChest_04_C",         ativo = false, tamanho = 1.0 },
    { nome = "Caixa de Madeira",                classe = "BP_BuildObject_Box_Wood_C",             ativo = false, tamanho = 1.0 },
    { nome = "Barril de Madeira",               classe = "BP_BuildObject_Barrel_Wood_C",          ativo = false, tamanho = 1.0 },
    { nome = "Prateleira de Madeira",           classe = "BP_BuildObject_Shelf_Wood_C",           ativo = false, tamanho = 1.0 },
    { nome = "Barril com Prateleira de Madeira", classe = "BP_BuildObject_Shelf_Cask_Wood_C",      ativo = false, tamanho = 1.0 },
    { nome = "Prateleira de Parede de Madeira", classe = "BP_BuildObject_Shelf_Hang01_Wood_C",    ativo = false, tamanho = 1.0 },
    { nome = "Estante Antiga",                  classe = "BP_BuildObject_Shelf01_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Guarda-Roupa Antigo",             classe = "BP_BuildObject_Shelf02_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Armário Antigo",                  classe = "BP_BuildObject_Shelf03_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Mesa de Cabeceira Antiga",        classe = "BP_BuildObject_Shelf04_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Cômoda Antiga",                   classe = "BP_BuildObject_Shelf05_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Cômoda Larga e Baixa Antiga",     classe = "BP_BuildObject_Shelf06_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Cômoda Grande Antiga",            classe = "BP_BuildObject_Shelf07_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Cômoda de Parede Antiga",         classe = "BP_BuildObject_Shelf01_Wall_Stone_C",   ativo = false, tamanho = 1.0 },
    { nome = "Prateleira Metálica",             classe = "BP_BuildObject_Shelf01_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Prateleira Metálica Horizontal",  classe = "BP_BuildObject_Shelf02_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Prateleira de Parede de Ferro",   classe = "BP_BuildObject_Shelf01_Wall_Iron_C",    ativo = false, tamanho = 1.0 },
    { nome = "Armário Laranja",                 classe = "BP_BuildObject_Shelf03_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Armário",                         classe = "BP_BuildObject_Shelf04_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Contêiner Grande",                classe = "BP_BuildObject_Container01_Iron_C",     ativo = false, tamanho = 1.0 },
    { nome = "Contêiner Pequeno",               classe = "BP_BuildObject_Box01_Iron_C",           ativo = false, tamanho = 1.0 },
    { nome = "Contêiner com Pano",              classe = "BP_BuildObject_Box02_Iron_C",           ativo = false, tamanho = 1.0 },
    { nome = "Armário",                         classe = "BP_BuildObject_Tansu_C",                ativo = false, tamanho = 1.0 },

    -- ---------- COMIDA (16) ----------
    { nome = "Fogueira",                        classe = "BP_BuildObject_CampFire_C",           ativo = false, tamanho = 1.0 },
    { nome = "Panela",                          classe = "BP_BuildObject_CookingStove_C",       ativo = false, tamanho = 1.0 },
    { nome = "Cozinha Elétrica",                classe = "BP_BuildObject_ElectricKitchen_C",    ativo = false, tamanho = 1.0 },
    { nome = "Cozinha Grande",                  classe = "BP_BuildObject_HugeKitchen_C",        ativo = false, tamanho = 1.0 },
    { nome = "Cozinha da Civilização Antiga",   classe = "BP_BuildObject_AncientCookingStove_C", ativo = false, tamanho = 1.0 },
    { nome = "Ração",                           classe = "BP_BuildObject_PalFoodBox_C",         ativo = false, tamanho = 1.0 },
    { nome = "Caixa de Ração Refrigerada",      classe = "BP_BuildObject_PalFoodBoxCool_C",     ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Frutinhas",          classe = "BP_BuildObject_FarmBlockV2_Berries_C", ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Trigo",              classe = "BP_BuildObject_FarmBlockV2_wheet_C",  ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Tomate",             classe = "BP_BuildObject_FarmBlockV2_tomato_C", ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Alface",             classe = "BP_BuildObject_FarmBlockV2_Lettuce_C", ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Batatas",            classe = "BP_BuildObject_FarmBlockV2_Potato_C", ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Cenouras",           classe = "BP_BuildObject_FarmBlockV2_Carrot_C", ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Cebolas",            classe = "BP_BuildObject_FarmBlockV2_Onion_C",  ativo = false, tamanho = 1.0 },
    { nome = "Plantação de Frutos de Técnica",  classe = "BP_BuildObject_Farm_SkillFruits_C",   ativo = false, tamanho = 1.0 },
    { nome = "Dispositivo de Plantio da Civilização Antiga", classe = "BP_BuildObject_FarmBlockRecipe_C",    ativo = false, tamanho = 1.0 },

    -- ---------- PAL (23) ----------
    { nome = "Caixa de Pal",                    classe = "BP_BuildObject_PalBoxV2_C",                            ativo = false, tamanho = 1.0 },
    { nome = "Caixa Global de Pals",            classe = "BP_BuildObject_GlobalPalStorage_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Armazenamento Dimensional de Pals", classe = "BP_BuildObject_DimensionPalStorage_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Terminal para Operar Caixa de Pals", classe = "BP_BuildObject_BaseCampWorkerExtraStation_C",          ativo = false, tamanho = 1.0 },
    { nome = "Plataforma de Monitoramento",     classe = "BP_BuildObject_BaseCampWorkHard_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Plataforma de Monitoramento Requintada", classe = "BP_BuildObject_BaseCampWorkHard_02_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Plataforma de Monitoramento da Civilização Antiga", classe = "BP_BuildObject_BaseCampWorkHard_03_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Laboratório de Pesquisa de Trabalho de Pals", classe = "BP_BuildObject_Lab_C",                                 ativo = false, tamanho = 1.0 },
    { nome = "Escritório de Expedição de Pals", classe = "BP_BuildObject_Expedition_C",                          ativo = false, tamanho = 1.0 },   -- [MiniBuilds]
    { nome = "Estátua da Força",                classe = "BP_BuildObject_BuildableGoddessStatue_C",              ativo = false, tamanho = 1.0 },
    { nome = "Casulo de Condensação de Pal",    classe = "BP_BuildObject_CharacterRankUp_C",                     ativo = false, tamanho = 1.0 },
    { nome = "Mesa de Operação de Pals",        classe = "BP_BuildObject_OperatingTable_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Fazenda de Acasalamento",         classe = "BP_BuildObject_BreedFarm_C",                           ativo = false, tamanho = 1.0 },   -- [MiniBuilds]
    { nome = "Fazenda de Criação",              classe = "BP_BuildObject_MonsterFarm_C",                         ativo = false, tamanho = 1.0 },   -- [MiniBuilds]
    { nome = "Incubadora de Ovos",              classe = "BP_BuildObject_HatchingPalEgg_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Incubadora de Ovos Elétrica",     classe = "BP_BuildObject_ElectricHatchingPalEgg_C",              ativo = false, tamanho = 1.0 },
    { nome = "Máquina Incubadora de Ovos Grande", classe = "BP_BuildObject_MultiHatchingPalEgg_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Incubadora de Ovos Elétrica Grande", classe = "BP_BuildObject_MultiElectricHatchingPalEgg_C",         ativo = false, tamanho = 1.0 },
    { nome = "Reprodutor da Civilização Antiga", classe = "BP_BuildObject_MultiElectricHatchingPalEggWithBreed_C", ativo = false, tamanho = 1.0 },
    { nome = "Dispositivo de Enfeite de Pal",   classe = "BP_BuildObject_CharacterSkinChange_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Gaiola para Apreciação",          classe = "BP_BuildObject_DisplayCharacter_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Transportador para Talho de Pal", classe = "BP_BuildObject_DismantlingConveyor_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Altar de Invocação",              classe = "BP_BuildObject_Altar_C",                               ativo = false, tamanho = 1.0 },

    -- ---------- INFRAESTRUTURA (25) ----------
    { nome = "Cama Simples",                    classe = "BP_BuildObject_PlayerBed_02_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Cama de Luxo",                    classe = "BP_BuildObject_PlayerBed_03_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Cama de Palha para Pals",         classe = "BP_BuildObject_MedicalPalBed_02_C",               ativo = false, tamanho = 1.0 },
    { nome = "Cama Macia para Pals",            classe = "BP_BuildObject_MedicalPalBed_03_C",               ativo = false, tamanho = 1.0 },
    { nome = "Cama Grande para Pals",           classe = "BP_BuildObject_MedicalPalBed_04_C",               ativo = false, tamanho = 1.0 },
    { nome = "Cápsula de Pals de Civilização Avançada", classe = "BP_BuildObject_MedicalPalBed_05_C",               ativo = false, tamanho = 1.0 },
    { nome = "Cama para Pals da Civilização Antiga", classe = "BP_BuildObject_MedicalPalBed_06_C",               ativo = false, tamanho = 1.0 },
    { nome = "Gerador Elétrico Manual",         classe = "BP_BuildObject_EnergyGenerator_Electric_Manual_C", ativo = false, tamanho = 1.0 },
    { nome = "Gerador Elétrico",                classe = "BP_BuildObject_EnergyGenerator_Electric_C",       ativo = false, tamanho = 1.0 },
    { nome = "Gerador Elétrico Grande",         classe = "BP_BuildObject_EnergyGenerator_Large_C",          ativo = false, tamanho = 1.0 },
    { nome = "Gerador Elétrico da Civilização Antiga", classe = "BP_BuildObject_AncientEnergyGenerator_C",         ativo = false, tamanho = 1.0 },
    { nome = "Capacitor",                       classe = "BP_BuildObject_EnergyStorage_Electric_C",         ativo = false, tamanho = 1.0 },
    { nome = "Aquecedor a Fogo",                classe = "BP_BuildObject_HeaterMedieval_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Resfriador a Gelo",               classe = "BP_BuildObject_CoolerMedieval_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Aquecedor Elétrico",              classe = "BP_BuildObject_HeaterElectric_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Resfriador Elétrico",             classe = "BP_BuildObject_CoolerElectric_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Condicionador de Ar da Civilização Antiga", classe = "BP_BuildObject_CoolerAncient_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Águas Termais",                   classe = "BP_BuildObject_Spa_C",                            ativo = false, tamanho = 1.0 },
    { nome = "Águas Termais de Luxo",           classe = "BP_BuildObject_Spa_2_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Águas Termais Japonesas",         classe = "BP_BuildObject_Spa_3_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Água Termal da Civilização Antiga", classe = "BP_BuildObject_Spa_4_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Clínica",                         classe = "BP_BuildObject_Clinic_C",                         ativo = false, tamanho = 1.0 },
    { nome = "Clínica da Civilização Antiga",   classe = "BP_BuildObject_Clinic_02_C",                      ativo = false, tamanho = 1.0 },
    { nome = "Armário de Remédios",             classe = "BP_BuildObject_PalMedicineBox_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Estátua da Águia Gigante",        classe = "BP_BuildObject_FastTravelPoint_C",                ativo = false, tamanho = 1.0 },

    -- ---------- MOBILIA (159) ----------
    { nome = "Mesa Quadrada",                   classe = "BP_BuildObject_TableSquare_Wood_C",        ativo = false, tamanho = 1.0 },
    { nome = "Mesa Quadrada Arrumada",          classe = "BP_BuildObject_TableSquare_Wood_None_C",   ativo = false, tamanho = 1.0 },
    { nome = "Mesa Redonda",                    classe = "BP_BuildObject_TableCircular_Wood_C",      ativo = false, tamanho = 1.0 },
    { nome = "Mesa Redonda Arrumada",           classe = "BP_BuildObject_TableCircular_Wood_None_C", ativo = false, tamanho = 1.0 },
    { nome = "Balcão de Madeira",               classe = "BP_BuildObject_Counter_Wood_C",            ativo = false, tamanho = 1.0 },
    { nome = "Escrivaninha Antiga",             classe = "BP_BuildObject_Desk01_Stone_C",            ativo = false, tamanho = 1.0 },
    { nome = "Mesa Redonda Antiga",             classe = "BP_BuildObject_TableCircular01_Stone_C",   ativo = false, tamanho = 1.0 },
    { nome = "Mesa Redonda de Ferro",           classe = "BP_BuildObject_TableCircular01_Iron_C",    ativo = false, tamanho = 1.0 },
    { nome = "Escrivaninha de Ferro",           classe = "BP_BuildObject_Desk01_Iron_C",             ativo = false, tamanho = 1.0 },
    { nome = "Mesa de Canto de Pau-Ferro",      classe = "BP_BuildObject_TableSide01_Iron_C",        ativo = false, tamanho = 1.0 },
    { nome = "Mesa de Pau-Ferro",               classe = "BP_BuildObject_TableSquare01_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Mesa Baixa de Pau-Ferro",         classe = "BP_BuildObject_TableSquare02_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Escrivaninha",                    classe = "BP_BuildObject_Fudukue_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Escrivaninha de Laboratório",     classe = "BP_BuildObject_SF_Desk_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Banco de Madeira",                classe = "BP_BuildObject_Bench_Wood_C",              ativo = false, tamanho = 1.0 },
    { nome = "Banqueta de Madeira",             classe = "BP_BuildObject_Stool_Wood_C",              ativo = false, tamanho = 1.0 },
    { nome = "Banqueta Alta de Madeira",        classe = "BP_BuildObject_Stool_High_Wood_C",         ativo = false, tamanho = 1.0 },
    { nome = "Cadeira de Madeira",              classe = "BP_BuildObject_Chair01_Wood_C",            ativo = false, tamanho = 1.0 },
    { nome = "Cadeira de Madeira Antiga",       classe = "BP_BuildObject_Chair01_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Cadeira Verde de Madeira Antiga", classe = "BP_BuildObject_Chair02_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Banqueta Antiga",                 classe = "BP_BuildObject_Stool01_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Poltrona Antiga",                 classe = "BP_BuildObject_Sofa01_Stone_C",            ativo = false, tamanho = 1.0 },
    { nome = "Sofá Antigo para Duas Pessoas",   classe = "BP_BuildObject_Sofa02_Stone_C",            ativo = false, tamanho = 1.0 },
    { nome = "Divã Antigo",                     classe = "BP_BuildObject_Sofa03_Stone_C",            ativo = false, tamanho = 1.0 },
    { nome = "Banqueta de Ferro",               classe = "BP_BuildObject_Stool01_Iron_C",            ativo = false, tamanho = 1.0 },
    { nome = "Cadeira de Ferro",                classe = "BP_BuildObject_Chair02_Iron_C",            ativo = false, tamanho = 1.0 },
    { nome = "Cadeira de Couro",                classe = "BP_BuildObject_Chair01_Iron_C",            ativo = false, tamanho = 1.0 },
    { nome = "Poltrona de Couro",               classe = "BP_BuildObject_Sofa01_Iron_C",             ativo = false, tamanho = 1.0 },
    { nome = "Sofá de Couro para Duas Pessoas", classe = "BP_BuildObject_Sofa02_Iron_C",             ativo = false, tamanho = 1.0 },
    { nome = "Cadeira Sapo",                    classe = "BP_BuildObject_Chair01_Pal_C",             ativo = false, tamanho = 1.0 },
    { nome = "Cadeira sem pernas",              classe = "BP_BuildObject_Zaisu_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Almofada",                        classe = "BP_BuildObject_Zabuton_C",                 ativo = false, tamanho = 1.0 },
    { nome = "Cadeira de Laboratório",          classe = "BP_BuildObject_SF_Chair_C",                ativo = false, tamanho = 1.0 },
    { nome = "Tapete Antigo",                   classe = "BP_BuildObject_Rug01_Stone_C",             ativo = false, tamanho = 1.0 },
    { nome = "Tapete Vermelho Antigo",          classe = "BP_BuildObject_Rug02_Stone_C",             ativo = false, tamanho = 1.0 },
    { nome = "Tapete Verde Antigo",             classe = "BP_BuildObject_Rug03_Stone_C",             ativo = false, tamanho = 1.0 },
    { nome = "Tapete Comprido Antigo",          classe = "BP_BuildObject_Rug04_Stone_C",             ativo = false, tamanho = 1.0 },
    { nome = "pt-BR_Text",                      classe = "BP_BuildObject_Rug_Wood_C",                ativo = false, tamanho = 1.0 },
    { nome = "Prateleira de Parede Decorativa de Madeira", classe = "BP_BuildObject_Shelf_Hang02_Wood_C",       ativo = false, tamanho = 1.0 },
    { nome = "Espelho de Parede Antigo",        classe = "BP_BuildObject_Mirror01_Wall_Stone_C",     ativo = false, tamanho = 1.0 },
    { nome = "Cortina Antiga",                  classe = "BP_BuildObject_Curtain01_Wall_Stone_C",    ativo = false, tamanho = 1.0 },
    { nome = "Relógio de Parede",               classe = "BP_BuildObject_Clock01_Wall_Iron_C",       ativo = false, tamanho = 1.0 },
    { nome = "Trepadeira Pequena de Parede",    classe = "BP_BuildObject_Ivy02_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Trepadeira Grande de Parede",     classe = "BP_BuildObject_Ivy01_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Trepadeira Horizontal de Parede", classe = "BP_BuildObject_Ivy03_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Placa de Saída de Emergência para Parede", classe = "BP_BuildObject_SignExit_Wall_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Placa de Saída de Emergência para Teto", classe = "BP_BuildObject_SignExit_Ceiling_Iron_C",   ativo = false, tamanho = 1.0 },
    { nome = "Pergaminho de parede",            classe = "BP_BuildObject_Kakejiku_C",                ativo = false, tamanho = 1.0 },
    { nome = "Planta Ornamental",               classe = "BP_BuildObject_Plant01_Plant_C",           ativo = false, tamanho = 1.0 },
    { nome = "Planta Ornamental com Banco",     classe = "BP_BuildObject_Plant02_Plant_C",           ativo = false, tamanho = 1.0 },
    { nome = "Planta Ornamental de Mesa",       classe = "BP_BuildObject_Plant03_Plant_C",           ativo = false, tamanho = 1.0 },
    { nome = "Planta Ornamental de Vaso",       classe = "BP_BuildObject_Plant04_Plant_C",           ativo = false, tamanho = 1.0 },
    { nome = "Bonsai",                          classe = "BP_BuildObject_Bonsai_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Arranjo floral",                  classe = "BP_BuildObject_Seika_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial A",             classe = "BP_BuildObject_FurnitureTree01_Green_C",   ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial B",             classe = "BP_BuildObject_FurnitureTree02_Green_C",   ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial C",             classe = "BP_BuildObject_FurnitureTree03_Green_C",   ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Folhas Vermelhas A", classe = "BP_BuildObject_FurnitureTree01_Red_C",     ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Folhas Vermelhas B", classe = "BP_BuildObject_FurnitureTree02_Red_C",     ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Folhas Vermelhas C", classe = "BP_BuildObject_FurnitureTree03_Red_C",     ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Folhas Amarelas A", classe = "BP_BuildObject_FurnitureTree01_Yellow_C",  ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Folhas Amarelas B", classe = "BP_BuildObject_FurnitureTree02_Yellow_C",  ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Folhas Amarelas C", classe = "BP_BuildObject_FurnitureTree03_Yellow_C",  ativo = false, tamanho = 1.0 },
    { nome = "Cerejeira Artificial A",          classe = "BP_BuildObject_FurnitureTree01_Cherry_C",  ativo = false, tamanho = 1.0 },
    { nome = "Cerejeira Artificial B",          classe = "BP_BuildObject_FurnitureTree02_Cherry_C",  ativo = false, tamanho = 1.0 },
    { nome = "Cerejeira Artificial C",          classe = "BP_BuildObject_FurnitureTree03_Cherry_C",  ativo = false, tamanho = 1.0 },
    { nome = "Árvore Tropical Artificial A",    classe = "BP_BuildObject_FurnitureTree01_Tropical_C", ativo = false, tamanho = 1.0 },
    { nome = "Árvore Tropical Artificial B",    classe = "BP_BuildObject_FurnitureTree02_Tropical_C", ativo = false, tamanho = 1.0 },
    { nome = "Árvore Tropical Artificial C",    classe = "BP_BuildObject_FurnitureTree03_Tropical_C", ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial Coberta de Neve A", classe = "BP_BuildObject_FurnitureTree01_Snow_C",    ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial Coberta de Neve B", classe = "BP_BuildObject_FurnitureTree02_Snow_C",    ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial Coberta de Neve C", classe = "BP_BuildObject_FurnitureTree03_Snow_C",    ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Deserto A",  classe = "BP_BuildObject_FurnitureTree01_Desert_C",  ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Deserto B",  classe = "BP_BuildObject_FurnitureTree02_Desert_C",  ativo = false, tamanho = 1.0 },
    { nome = "Árvore Artificial de Deserto C",  classe = "BP_BuildObject_FurnitureTree03_Desert_C",  ativo = false, tamanho = 1.0 },
    { nome = "Bambu Artificial A",              classe = "BP_BuildObject_FurnitureTree01_Bamboo_C",  ativo = false, tamanho = 1.0 },
    { nome = "Bambu Artificial B",              classe = "BP_BuildObject_FurnitureTree02_Bamboo_C",  ativo = false, tamanho = 1.0 },
    { nome = "Bambu Artificial C",              classe = "BP_BuildObject_FurnitureTree03_Bamboo_C",  ativo = false, tamanho = 1.0 },
    { nome = "Arbusto Artificial",              classe = "BP_BuildObject_FurnitureBush01_Green_C",   ativo = false, tamanho = 1.0 },
    { nome = "Arbusto Artificial de Folhas Amarelas", classe = "BP_BuildObject_FurnitureBush01_Yellow_C",  ativo = false, tamanho = 1.0 },
    { nome = "Arbusto Artificial com Flores A", classe = "BP_BuildObject_FurnitureBush01_Flower_C",  ativo = false, tamanho = 1.0 },
    { nome = "Penteadeira Antiga",              classe = "BP_BuildObject_TableDresser01_Stone_C",    ativo = false, tamanho = 1.0 },
    { nome = "Arbusto Artificial com Flores B", classe = "BP_BuildObject_FurnitureBush02_Flower_C",  ativo = false, tamanho = 1.0 },
    { nome = "Banheira Antiga",                 classe = "BP_BuildObject_BathTub_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Arbusto Tropical Artificial",     classe = "BP_BuildObject_FurnitureBush01_Tropical_C", ativo = false, tamanho = 1.0 },
    { nome = "Cesto Antigo",                    classe = "BP_BuildObject_Box01_Stone_C",             ativo = false, tamanho = 1.0 },
    { nome = "Arbusto Artificial Branco",       classe = "BP_BuildObject_FurnitureBush01_Snow_C",    ativo = false, tamanho = 1.0 },
    { nome = "Partição Antiga",                 classe = "BP_BuildObject_Partition_Stone_C",         ativo = false, tamanho = 1.0 },
    { nome = "Porta-Toalha Antigo",             classe = "BP_BuildObject_TowlRack01_Stone_C",        ativo = false, tamanho = 1.0 },
    { nome = "Espelho Oval Antigo",             classe = "BP_BuildObject_Mirror01_Stone_C",          ativo = false, tamanho = 1.0 },
    { nome = "Espelho Antigo",                  classe = "BP_BuildObject_Mirror02_Stone_C",          ativo = false, tamanho = 1.0 },
    { nome = "Piano de Cauda",                  classe = "BP_BuildObject_Piano01_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Piano Vertical",                  classe = "BP_BuildObject_Piano02_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Pia de Banheiro Antiga",          classe = "BP_BuildObject_TableSink01_Stone_C",       ativo = false, tamanho = 1.0 },
    { nome = "Vaso Sanitário Antigo",           classe = "BP_BuildObject_Toilet01_Stone_C",          ativo = false, tamanho = 1.0 },
    { nome = "Porta-Papel Higiênico Antigo",    classe = "BP_BuildObject_ToiletHolder01_Stone_C",    ativo = false, tamanho = 1.0 },
    { nome = "Globo Terrestre Antigo",          classe = "BP_BuildObject_Globe01_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Aquecedor Antigo",                classe = "BP_BuildObject_Stove01_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Relógio de Pêndulo Antigo",       classe = "BP_BuildObject_Clock01_Stone_C",           ativo = false, tamanho = 1.0 },
    { nome = "Carretel de Cabo",                classe = "BP_BuildObject_CableCoil01_Iron_C",        ativo = false, tamanho = 1.0 },
    { nome = "Saco de Lixo",                    classe = "BP_BuildObject_GarbageBag_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Cano de Cerâmica",                classe = "BP_BuildObject_PipeClay01_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Pneu",                            classe = "BP_BuildObject_Tire01_Iron_C",             ativo = false, tamanho = 1.0 },
    { nome = "Tonel Vermelho",                  classe = "BP_BuildObject_Barrel01_Iron_C",           ativo = false, tamanho = 1.0 },
    { nome = "Tonel Azul",                      classe = "BP_BuildObject_Barrel02_Iron_C",           ativo = false, tamanho = 1.0 },
    { nome = "Tonel Verde",                     classe = "BP_BuildObject_Barrel03_Iron_C",           ativo = false, tamanho = 1.0 },
    { nome = "Rede de Futebol",                 classe = "BP_BuildObject_GoalSoccer_Iron_C",         ativo = false, tamanho = 1.0 },
    { nome = "Máquina de Garra",                classe = "BP_BuildObject_MachineGame01_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Máquina de Fliperama",            classe = "BP_BuildObject_ArcadeVideoGame_C",         ativo = false, tamanho = 1.0 },
    { nome = "Máquina Automática de Refrigerante", classe = "BP_BuildObject_MachineVending01_Iron_C",   ativo = false, tamanho = 1.0 },
    { nome = "Televisão Antiga",                classe = "BP_BuildObject_Television01_Iron_C",       ativo = false, tamanho = 1.0 },
    { nome = "Cone",                            classe = "BP_BuildObject_TrafficCone01_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Cone de Trânsito Roliço",         classe = "BP_BuildObject_TrafficCone02_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Cone de Trânsito Delgado",        classe = "BP_BuildObject_TrafficCone03_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Semáforo",                        classe = "BP_BuildObject_TrafficLight01_Iron_C",     ativo = false, tamanho = 1.0 },
    { nome = "Placa para Proibir Passagem de Pals", classe = "BP_BuildObject_TrafficSign01_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Placa de Parada Obrigatória",     classe = "BP_BuildObject_TrafficSign02_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Placa de Eikthyrdeers na Pista",  classe = "BP_BuildObject_TrafficSign03_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Placa de Mammorests na Pista",    classe = "BP_BuildObject_TrafficSign04_Iron_C",      ativo = false, tamanho = 1.0 },
    { nome = "Barricada",                       classe = "BP_BuildObject_TrafficBarricade01_Iron_C", ativo = false, tamanho = 1.0 },
    { nome = "Barricada Laranja",               classe = "BP_BuildObject_TrafficBarricade02_Iron_C", ativo = false, tamanho = 1.0 },
    { nome = "Barricada Vermelha de Ferro",     classe = "BP_BuildObject_TrafficBarricade03_Iron_C", ativo = false, tamanho = 1.0 },
    { nome = "Barricada Branca de Ferro",       classe = "BP_BuildObject_TrafficBarricade04_Iron_C", ativo = false, tamanho = 1.0 },
    { nome = "Cerca de Ferro",                  classe = "BP_BuildObject_TrafficBarricade05_Iron_C", ativo = false, tamanho = 1.0 },
    { nome = "Cerca de Arame",                  classe = "BP_BuildObject_Wire_Fence_C",              ativo = false, tamanho = 1.0 },
    { nome = "Barricada de Madeira",            classe = "BP_BuildObject_WoodenBarricade_C",         ativo = false, tamanho = 1.0 },
    { nome = "Biombo",                          classe = "BP_BuildObject_Byobu_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Lareira de chão",                 classe = "BP_BuildObject_Irori_C",                   ativo = false, tamanho = 1.0 },
    { nome = "Lanterna de pedra",               classe = "BP_BuildObject_Toro_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Fonte de água de bambu",          classe = "BP_BuildObject_Shishiodoshi_C",            ativo = false, tamanho = 1.0 },
    { nome = "Incensário",                      classe = "BP_BuildObject_Koro_C",                    ativo = false, tamanho = 1.0 },
    { nome = "Rocha Artificial",                classe = "BP_BuildObject_FurnitureStone01_C",        ativo = false, tamanho = 1.0 },
    { nome = "Estátua de Jetragon",             classe = "BP_BuildObject_JetDragonStatue_C",         ativo = false, tamanho = 1.0 },
    { nome = "Estátua de Frostallion",          classe = "BP_BuildObject_IceHorseStatue_C",          ativo = false, tamanho = 1.0 },
    { nome = "Estátua de Yakumo",               classe = "BP_BuildObject_GuardianDogStatue_C",       ativo = false, tamanho = 1.0 },
    { nome = "Estátua de Lyleen",               classe = "BP_BuildObject_LilyQueenStatue_C",         ativo = false, tamanho = 1.0 },
    { nome = "Estátua do Senhor da Lua",        classe = "BP_BuildObject_YakushimaBoss002_Relic_C",  ativo = false, tamanho = 1.0 },
    { nome = "Estandarte dos Caçadores Clandestinos", classe = "BP_BuildObject_Hunter_Flag_C",             ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical dos Caçadores Clandestinos", classe = "BP_BuildObject_Hunter_Banner_C",           ativo = false, tamanho = 1.0 },
    { nome = "Bandeira dos Caçadores Clandestinos", classe = "BP_BuildObject_Hunter_GangFlag_C",         ativo = false, tamanho = 1.0 },
    { nome = "Estandarte da Associação de Proteção aos Pals", classe = "BP_BuildObject_Believer_Flag_C",           ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical da Associação de Proteção aos Pals", classe = "BP_BuildObject_Believer_Banner_C",         ativo = false, tamanho = 1.0 },
    { nome = "Bandeira da Associação de Proteção aos Pals", classe = "BP_BuildObject_ConservationGroupBannerA_C", ativo = false, tamanho = 1.0 },
    { nome = "Faixa da Associação de Proteção aos Pals", classe = "BP_BuildObject_ConservationGroupBannerB_C", ativo = false, tamanho = 1.0 },
    { nome = "Estandarte dos Amigos da Chama Eterna", classe = "BP_BuildObject_FireCult_Flag_C",           ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical dos Amigos da Chama Eterna", classe = "BP_BuildObject_FireCult_Banner_C",         ativo = false, tamanho = 1.0 },
    { nome = "Estandarte da Milícia Popular",   classe = "BP_BuildObject_Police_Flag_C",             ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical da Milícia Popular", classe = "BP_BuildObject_Police_Banner_C",           ativo = false, tamanho = 1.0 },
    { nome = "Estandarte da Unidade de Pesquisas Genéticas", classe = "BP_BuildObject_Scientist_Flag_C",          ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical da Unidade de Pesquisas Genéticas", classe = "BP_BuildObject_Scientist_Banner_C",        ativo = false, tamanho = 1.0 },
    { nome = "Estandarte do Bando das Flores e da Lua", classe = "BP_BuildObject_Ninja_Flag_C",              ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical do Bando das Flores e da Lua", classe = "BP_BuildObject_Ninja_Banner_C",            ativo = false, tamanho = 1.0 },
    { nome = "Estandarte do Povo Decaído",      classe = "BP_BuildObject_DarkIsland_Flag_C",         ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical do Povo Decaído",  classe = "BP_BuildObject_DarkIsland_Banner_C",       ativo = false, tamanho = 1.0 },
    { nome = "Estandarte da Aliança Celeste",   classe = "BP_BuildObject_SkyIsland_Flag_C",          ativo = false, tamanho = 1.0 },
    { nome = "Faixa Vertical da Aliança Celeste", classe = "BP_BuildObject_SkyIsland_Banner_C",        ativo = false, tamanho = 1.0 },
    { nome = "Banyan_Big",                      classe = "BP_BuildObject_Banyan_Big_C",              ativo = false, tamanho = 1.0 },
    { nome = "pt-BR_Text",                      classe = "BP_BuildObject_Decal_PalSticker_PinkCat_C", ativo = false, tamanho = 1.0 },
    { nome = "Jaula Vazia",                     classe = "BP_BuildObject_PalCage_C",                 ativo = false, tamanho = 1.0 },

    -- ---------- ILUMINACAO (22) ----------
    { nome = "Tocha Fixa",                      classe = "BP_BuildObject_TorchStand_C",             ativo = false, tamanho = 1.0 },
    { nome = "Lâmpada Fixa",                    classe = "BP_BuildObject_LampStand_C",              ativo = false, tamanho = 1.0 },
    { nome = "Lâmpada Grande Fixa",             classe = "BP_BuildObject_LampStandLarge_C",         ativo = false, tamanho = 1.0 },
    { nome = "Lareira",                         classe = "BP_BuildObject_Light_FirePlace01_C",      ativo = false, tamanho = 1.0 },
    { nome = "Aquecedor",                       classe = "BP_BuildObject_Light_FirePlace02_C",      ativo = false, tamanho = 1.0 },
    { nome = "Poste de Luz Simples",            classe = "BP_BuildObject_Light_LightPole01_C",      ativo = false, tamanho = 1.0 },
    { nome = "Poste de Luz Duplo",              classe = "BP_BuildObject_Light_LightPole02_C",      ativo = false, tamanho = 1.0 },
    { nome = "Poste de Luz Retrô",              classe = "BP_BuildObject_Light_LightPole03_C",      ativo = false, tamanho = 1.0 },
    { nome = "Poste de Luz Chique",             classe = "BP_BuildObject_Light_LightPole04_C",      ativo = false, tamanho = 1.0 },
    { nome = "Abajur Marrom Antigo",            classe = "BP_BuildObject_Light_FloorLamp01_C",      ativo = false, tamanho = 1.0 },
    { nome = "Abajur Vermelho Antigo",          classe = "BP_BuildObject_Light_FloorLamp02_C",      ativo = false, tamanho = 1.0 },
    { nome = "Lanterna de papel",               classe = "BP_BuildObject_Andon_C",                  ativo = false, tamanho = 1.0 },
    { nome = "Lanterna de Santuário",           classe = "BP_BuildObject_Light_Shrine_Lantern_C",   ativo = false, tamanho = 1.0 },
    { nome = "Castiçal Solene",                 classe = "BP_BuildObject_CandleStand_C",            ativo = false, tamanho = 1.0 },
    { nome = "Castiçal para Cerimônias",        classe = "BP_BuildObject_FireStand_C",              ativo = false, tamanho = 1.0 },
    { nome = "Tocha de Parede",                 classe = "BP_BuildObject_TorchHang_C",              ativo = false, tamanho = 1.0 },
    { nome = "Luminária de Parede",             classe = "BP_BuildObject_Light_CandleSticks_Wall_C", ativo = false, tamanho = 1.0 },
    { nome = "Tocha de Parede Solene",          classe = "BP_BuildObject_TorchHang02_C",            ativo = false, tamanho = 1.0 },
    { nome = "Lâmpada de Teto",                 classe = "BP_BuildObject_LampTop_C",                ativo = false, tamanho = 1.0 },
    { nome = "Lâmpada Grande de Teto",          classe = "BP_BuildObject_LampTopLarge_C",           ativo = false, tamanho = 1.0 },
    { nome = "Lustre",                          classe = "BP_BuildObject_Light_CandleSticks_Top_C", ativo = false, tamanho = 1.0 },
    { nome = "Lanterna de Papel Portátil",      classe = "BP_BuildObject_LanternTop_C",             ativo = false, tamanho = 1.0 },

    -- ---------- DEFESA (19) ----------
    { nome = "Armadilha de Laço",               classe = "BP_BuildObject_Trap_Noose_C",                                ativo = false, tamanho = 1.0 },
    { nome = "Armadilha de Urso (P)",           classe = "BP_BuildObject_Trap_LegHold_C",                              ativo = false, tamanho = 1.0 },
    { nome = "Armadilha de Urso (G)",           classe = "BP_BuildObject_Trap_LegHold_Big_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Mina Terrestre",                  classe = "BP_BuildObject_Trap_MineAttack_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Mina Elétrica",                   classe = "BP_BuildObject_Trap_MineElecShock_C",                        ativo = false, tamanho = 1.0 },
    { nome = "Mina Congelante",                 classe = "BP_BuildObject_Trap_MineFreeze_C",                           ativo = false, tamanho = 1.0 },
    { nome = "Saco de Areia",                   classe = "BP_BuildObject_DefenseWait_C",                               ativo = false, tamanho = 1.0 },
    { nome = "Besta Fixa",                      classe = "BP_BuildObjectDefenseBulletLauncher_BowGun_C",               ativo = false, tamanho = 1.0 },
    { nome = "Metralhadora Fixa",               classe = "BP_BuildObjectDefenseBulletLauncher_Machinegun_C",           ativo = false, tamanho = 1.0 },
    { nome = "Lança-Mísseis Fixo",              classe = "BP_BuildObjectDefenseBulletLauncher_Missile_C",              ativo = false, tamanho = 1.0 },
    { nome = "Torre da Civilização Antiga",     classe = "BP_BuildObjectDefenseBulletLauncher_Machinegun_AutoTurret_C", ativo = false, tamanho = 1.0 },
    { nome = "Sino de Alarme",                  classe = "BP_BuildObject_BaseCampBattleDirector_C",                    ativo = false, tamanho = 1.0 },
    { nome = "pt-BR_Text",                      classe = "BP_BuildObject_Trap_MovingPanel_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Barreira de Madeira",             classe = "BP_BuildObject_DefenseWall_Wood_C",                          ativo = false, tamanho = 1.0 },
    { nome = "Barreira de Pedra",               classe = "BP_BuildObject_DefenseWall_C",                               ativo = false, tamanho = 1.0 },
    { nome = "Barreira de Metal",               classe = "BP_BuildObject_DefenseWall_Metal_C",                         ativo = false, tamanho = 1.0 },
    { nome = "Portão de Madeira",               classe = "BP_BuildObject_Wood_Gate_C",                                 ativo = false, tamanho = 1.0 },
    { nome = "Portão de Pedra",                 classe = "BP_BuildObject_Stone_Gate_C",                                ativo = false, tamanho = 1.0 },
    { nome = "Portão de Metal",                 classe = "BP_BuildObject_Metal_Gate_C",                                ativo = false, tamanho = 1.0 },

    -- ---------- OUTROS (20) ----------
    { nome = "Chafariz",                        classe = "BP_BuildObject_Fountain_C",          ativo = false, tamanho = 1.0 },
    { nome = "Canteiro de Flores",              classe = "BP_BuildObject_FlowerBed_C",         ativo = false, tamanho = 1.0 },
    { nome = "Silo",                            classe = "BP_BuildObject_Silo_C",              ativo = false, tamanho = 1.0 },
    { nome = "Toco e Machado",                  classe = "BP_BuildObject_Stump_C",             ativo = false, tamanho = 1.0 },
    { nome = "Vagoneta de Garimpo",             classe = "BP_BuildObject_MiningTool_C",        ativo = false, tamanho = 1.0 },
    { nome = "Caldeirão de Bruxa",              classe = "BP_BuildObject_Cauldron_C",          ativo = false, tamanho = 1.0 },
    { nome = "Boneco de Neve",                  classe = "BP_BuildObject_Snowman_C",           ativo = false, tamanho = 1.0 },
    { nome = "Torre de Transmissão",            classe = "BP_BuildObject_TransmissionTower_C", ativo = false, tamanho = 1.0 },
    { nome = "Caixa de Ferramentas Grande",     classe = "BP_BuildObject_ToolBoxV1_C",         ativo = false, tamanho = 1.0 },
    { nome = "Pira da Chama Sagrada",           classe = "BP_BuildObject_OlympicCauldron_C",   ativo = false, tamanho = 1.0 },
    { nome = "Emissor de Ondas Alfa",           classe = "BP_BuildObject_SanityDecrease1_C",   ativo = false, tamanho = 1.0 },
    { nome = "Emissor de Ondas Beta",           classe = "BP_BuildObject_WorkSpeedIncrease1_C", ativo = false, tamanho = 1.0 },
    { nome = "Mercado de Pulgas (Pals)",        classe = "BP_BuildObject_PalBooth_C",          ativo = false, tamanho = 1.0 },
    { nome = "Mercado de Pulgas (Itens)",       classe = "BP_BuildObject_ItemBooth_C",         ativo = false, tamanho = 1.0 },
    { nome = "Boneco de Pancada",               classe = "BP_BuildObject_DamagedScarecrow_C",  ativo = false, tamanho = 1.0 },
    { nome = "Placa",                           classe = "BP_BuildObject_Signboard_C",         ativo = false, tamanho = 1.0 },
    { nome = "Placa de Parede",                 classe = "BP_BuildObject_WallSignboard_C",     ativo = false, tamanho = 1.0 },
    { nome = "Lápide",                          classe = "BP_BuildObject_Headstone_C",         ativo = false, tamanho = 1.0 },
    { nome = "pt-BR_Text",                      classe = "BP_BuildObject_WoodCreator_C",       ativo = false, tamanho = 1.0 },
    { nome = "DamagedScarecrow_Test",           classe = "BP_BuildObject_DamagedScarecrow_2_C", ativo = false, tamanho = 1.0 },
}
