-- =====================================================================
--  BuildSizes - CONFIG   (edit, save, then press F7 in game)
--
--  HOW TO USE
--    1. Find the structure below and change  enabled = false  to  enabled = true
--    2. Pick a  size :  1.0 = normal | 0.65 = smaller | 0.3 = tiny
--                       1.5 = bigger  (you can scale UP too)
--    3. Save this file and press  F7  in game
--    4. In build mode, aim until the ghost is placed on valid ground. Then
--       RE-SELECT the structure in the menu -- it spawns at the new size.
--
--  Scaling is PROPORTIONAL: size, part positions and the footprint all shrink
--  by the same factor. That is why you can stack and butt them together
--  without weird collision.
--
--  Applies to what you build AFTERWARDS. Already-placed structures are untouched.
--
--  Adding one by hand: copy a line and swap the class (BP_BuildObject_<x>_C).
--
--  The 3 marked [MiniBuilds] are handled by that mod -- leave them false, or
--  the scale gets applied twice.
-- =====================================================================
return {

    -- ---------- PRODUCTION (45) ----------
    { name = "Primitive Workbench",             class = "BP_BuildObject_WorkBench_C",             enabled = true,  size = 0.65 },  -- <== EXAMPLE, TURNED ON
    { name = "Repair Bench",                    class = "BP_BuildObject_RepairBench_C",           enabled = false, size = 1.0 },
    { name = "Pal Gear Workbench",              class = "BP_BuildObject_WorkBench_SkillUnlock_C", enabled = false, size = 1.0 },
    { name = "High-Quality Workbench",          class = "BP_BuildObject_Factory_Hard_01_C",       enabled = false, size = 1.0 },
    { name = "Production Assembly Line",        class = "BP_BuildObject_Factory_Hard_02_C",       enabled = false, size = 1.0 },
    { name = "Production Assembly Line II",     class = "BP_BuildObject_Factory_Hard_03_C",       enabled = false, size = 1.0 },
    { name = "Advanced Workshop",               class = "BP_BuildObject_Factory_Hard_4_C",        enabled = false, size = 1.0 },
    { name = "Ancient Workbench",               class = "BP_BuildObject_AncientWorkBench_C",      enabled = false, size = 1.0 },
    { name = "Drafting Table",                  class = "BP_BuildObject_CompositeDesk_C",         enabled = false, size = 1.0 },
    { name = "Gold Coin Assembly Line",         class = "BP_BuildObject_Factory_Money_C",         enabled = false, size = 1.0 },
    { name = "Ancient Relic Recycler",          class = "BP_BuildObject_AncientRelicRecycler_C",  enabled = false, size = 1.0 },
    { name = "Sphere Workbench",                class = "BP_BuildObject_SphereFactory_Black_01_C", enabled = false, size = 1.0 },
    { name = "Sphere Assembly Line",            class = "BP_BuildObject_SphereFactory_Black_02_C", enabled = false, size = 1.0 },
    { name = "Sphere Assembly Line II",         class = "BP_BuildObject_SphereFactory_Black_03_C", enabled = false, size = 1.0 },
    { name = "Advanced Sphere Assembly Line",   class = "BP_BuildObject_SphereFactory_Black_04_C", enabled = false, size = 1.0 },
    { name = "Weapon Workbench",                class = "BP_BuildObject_WeaponFactory_Dirty_01_C", enabled = false, size = 1.0 },
    { name = "Weapon Assembly Line",            class = "BP_BuildObject_WeaponFactory_Dirty_02_C", enabled = false, size = 1.0 },
    { name = "Weapon Assembly Line II",         class = "BP_BuildObject_WeaponFactory_Dirty_03_C", enabled = false, size = 1.0 },
    { name = "Advanced Weapon Assembly Line",   class = "BP_BuildObject_WeaponFactory_Dirty_4_C", enabled = false, size = 1.0 },
    { name = "Logging Site",                    class = "BP_BuildObject_StationDeforest2_C",      enabled = false, size = 1.0 },
    { name = "Logging Site II",                 class = "BP_BuildObject_StationDeforest3_C",      enabled = false, size = 1.0 },
    { name = "Stone Pit",                       class = "BP_BuildObject_StonePit_C",              enabled = false, size = 1.0 },
    { name = "Ore Mining Site",                 class = "BP_BuildObject_CopperPit_C",             enabled = false, size = 1.0 },
    { name = "Ore Mining Site II",              class = "BP_BuildObject_CopperPit_2_C",           enabled = false, size = 1.0 },
    { name = "Coal Quarry",                     class = "BP_BuildObject_CoalPit_C",               enabled = false, size = 1.0 },
    { name = "Sulfur Quarry",                   class = "BP_BuildObject_SulfurPit_C",             enabled = false, size = 1.0 },
    { name = "Pure Quartz Quarry",              class = "BP_BuildObject_QuartzPit_C",             enabled = false, size = 1.0 },
    { name = "Crude Oil Extractor",             class = "BP_BuildObject_OilPump_C",               enabled = false, size = 1.0 },
    { name = "High-Pressure Crude Oil Extractor", class = "BP_BuildObject_OilPump02_C",             enabled = false, size = 1.0 },
    { name = "Hexolite Quartz Mine",            class = "BP_BuildObject_CrystalPit_C",            enabled = false, size = 1.0 },
    { name = "Soralite Quarry",                 class = "BP_BuildObject_SkyIslandOrePit_C",       enabled = false, size = 1.0 },
    { name = "Ancient Material Synthesizer",    class = "BP_BuildObject_AncientMultiProduct_C",   enabled = false, size = 1.0 },
    { name = "Primitive Furnace",               class = "BP_BuildObject_BlastFurnace_C",          enabled = false, size = 1.0 },
    { name = "Improved Furnace",                class = "BP_BuildObject_BlastFurnace_2_C",        enabled = false, size = 1.0 },
    { name = "Electric Furnace",                class = "BP_BuildObject_BlastFurnace3_C",         enabled = false, size = 1.0 },
    { name = "Gigantic Furnace",                class = "BP_BuildObject_BlastFurnace4_C",         enabled = false, size = 1.0 },
    { name = "Ancient Furnace",                 class = "BP_BuildObject_AncientBlastFurnace_C",   enabled = false, size = 1.0 },
    { name = "Mill",                            class = "BP_BuildObject_FlourMill_C",             enabled = false, size = 1.0 },
    { name = "Crusher",                         class = "BP_BuildObject_Crusher_C",               enabled = false, size = 1.0 },
    { name = "Cryogenic Crusher",               class = "BP_BuildObject_IceCrusher_C",            enabled = false, size = 1.0 },
    { name = "Medieval Medicine Workbench",     class = "BP_BuildObject_MedicineFacility_01_C",   enabled = false, size = 1.0 },
    { name = "Electric Medicine Workbench",     class = "BP_BuildObject_MedicineFacility_02_C",   enabled = false, size = 1.0 },
    { name = "Advanced Medicine Workbench",     class = "BP_BuildObject_MedicineFacility_03_C",   enabled = false, size = 1.0 },
    { name = "Fishing Pond",                    class = "BP_BuildObject_FishingPond01_C",         enabled = false, size = 1.0 },
    { name = "Large Fishing Pond",              class = "BP_BuildObject_FishingPond02_C",         enabled = false, size = 1.0 },

    -- ---------- FOUNDATION (134) ----------
    { name = "Wooden Foundation",               class = "BP_BuildObject_Wood_Foundation_C",                      enabled = false, size = 1.0 },
    { name = "Wooden Triangular Foundation",    class = "BP_BuildObject_Wood_TriangleFoundation_C",              enabled = false, size = 1.0 },
    { name = "Wooden Wall",                     class = "BP_BuildObject_Wood_Wall_V2_C",                         enabled = false, size = 1.0 },
    { name = "Wooden Wall and Window",          class = "BP_BuildObject_Wood_WindowWall_C",                      enabled = false, size = 1.0 },
    { name = "Wooden Door",                     class = "BP_BuildObject_Wood_DoorWall_C",                        enabled = false, size = 1.0 },
    { name = "Wooden Diagonal Wall",            class = "BP_BuildObject_Wood_DiagonalWall_C",                    enabled = false, size = 1.0 },
    { name = "Wooden Triangular Wall",          class = "BP_BuildObject_Wood_TriangleWall_C",                    enabled = false, size = 1.0 },
    { name = "Wooden Triangular Wall (Inverted)", class = "BP_BuildObject_Wood_TriangleWallReverse_C",             enabled = false, size = 1.0 },
    { name = "Wooden Roof",                     class = "BP_BuildObject_Wood_Roof_C",                            enabled = false, size = 1.0 },
    { name = "Wooden Triangular Roof",          class = "BP_BuildObject_Wood_TriangleRoof_C",                    enabled = false, size = 1.0 },
    { name = "Wooden Slanted Roof",             class = "BP_BuildObject_Wood_SlantedRoof_C",                     enabled = false, size = 1.0 },
    { name = "Wooden Slanted Triangular Roof",  class = "BP_BuildObject_Wood_SlopedRoofCorner_C",                enabled = false, size = 1.0 },
    { name = "Wooden Slanted Corner Roof (Inverted)", class = "BP_BuildObject_Wood_SlopedRoofCornerReverse_C",         enabled = false, size = 1.0 },
    { name = "Wooden Corner Roof",              class = "BP_BuildObject_Wood_TriangleStairsCorner_C",            enabled = false, size = 1.0 },
    { name = "Wooden Pyramid Roof",             class = "BP_BuildObject_Wood_PyramidRoof_C",                     enabled = false, size = 1.0 },
    { name = "Wooden Stairs",                   class = "BP_BuildObject_Wood_Stair_C",                           enabled = false, size = 1.0 },
    { name = "Wooden Pal Passage Entrance",     class = "BP_BuildObject_Wood_WallGate_C",                        enabled = false, size = 1.0 },
    { name = "Wooden Fence",                    class = "BP_BuildObject_Wood_Fence_C",                           enabled = false, size = 1.0 },
    { name = "Ladder",                          class = "BP_BuildObject_Wood_Ladder_C",                          enabled = false, size = 1.0 },
    { name = "Stone Foundation",                class = "BP_BuildObject_Stone_Foundation_C",                     enabled = false, size = 1.0 },
    { name = "Stone Triangular Foundation",     class = "BP_BuildObject_Stone_TriangleFoundation_C",             enabled = false, size = 1.0 },
    { name = "Stone Wall",                      class = "BP_BuildObject_Stone_Wall_V2_C",                        enabled = false, size = 1.0 },
    { name = "Stone Wall and Window",           class = "BP_BuildObject_Stone_WindowWall_C",                     enabled = false, size = 1.0 },
    { name = "Stone Door",                      class = "BP_BuildObject_Stone_DoorWall_C",                       enabled = false, size = 1.0 },
    { name = "Stone Diagonal Wall",             class = "BP_BuildObject_Stone_DiagonalWall_C",                   enabled = false, size = 1.0 },
    { name = "Stone Triangular Wall",           class = "BP_BuildObject_Stone_TriangleWall_C",                   enabled = false, size = 1.0 },
    { name = "Stone Triangular Wall (Inverted)", class = "BP_BuildObject_Stone_TriangleWallReverse_C",            enabled = false, size = 1.0 },
    { name = "Stone Roof",                      class = "BP_BuildObject_Stone_Roof_C",                           enabled = false, size = 1.0 },
    { name = "Stone Triangular Roof",           class = "BP_BuildObject_Stone_TriangleRoof_C",                   enabled = false, size = 1.0 },
    { name = "Stone Slanted Roof",              class = "BP_BuildObject_Stone_SlantedRoof_C",                    enabled = false, size = 1.0 },
    { name = "Stone Slanted Triangular Roof",   class = "BP_BuildObject_Stone_SlopedRoofCorner_C",               enabled = false, size = 1.0 },
    { name = "Stone Slanted Corner Roof (Inverted)", class = "BP_BuildObject_Stone_SlopedRoofCornerReverse_C",        enabled = false, size = 1.0 },
    { name = "Stone Corner Roof",               class = "BP_BuildObject_Stone_TriangleStairsCorner_C",           enabled = false, size = 1.0 },
    { name = "Stone Pyramid Roof",              class = "BP_BuildObject_Stone_PyramidRoof_C",                    enabled = false, size = 1.0 },
    { name = "Stone Stairs",                    class = "BP_BuildObject_Stone_Stair_C",                          enabled = false, size = 1.0 },
    { name = "Stone Pal Passage Entrance",      class = "BP_BuildObject_Stone_WallGate_C",                       enabled = false, size = 1.0 },
    { name = "Stone Fence",                     class = "BP_BuildObject_Stone_Fence_C",                          enabled = false, size = 1.0 },
    { name = "Metal Foundation",                class = "BP_BuildObject_Metal_Foundation_C",                     enabled = false, size = 1.0 },
    { name = "Metal Triangular Foundation",     class = "BP_BuildObject_Iron_TriangleFoundation_C",              enabled = false, size = 1.0 },
    { name = "Metal Wall",                      class = "BP_BuildObject_Metal_Wall_V2_C",                        enabled = false, size = 1.0 },
    { name = "Metal Wall and Window",           class = "BP_BuildObject_Metal_WindowWall_C",                     enabled = false, size = 1.0 },
    { name = "Metal Door",                      class = "BP_BuildObject_Metal_DoorWall_C",                       enabled = false, size = 1.0 },
    { name = "Metal Diagonal Wall",             class = "BP_BuildObject_Iron_DiagonalWall_C",                    enabled = false, size = 1.0 },
    { name = "Metal Triangular Wall",           class = "BP_BuildObject_Metal_TriangleWall_C",                   enabled = false, size = 1.0 },
    { name = "Metal Triangular Wall (Inverted)", class = "BP_BuildObject_Iron_TriangleWallReverse_C",             enabled = false, size = 1.0 },
    { name = "Metal Roof",                      class = "BP_BuildObject_Metal_Roof_C",                           enabled = false, size = 1.0 },
    { name = "Metal Triangular Roof",           class = "BP_BuildObject_Iron_TriangleRoof_C",                    enabled = false, size = 1.0 },
    { name = "Metal Slanted Roof",              class = "BP_BuildObject_Metal_SlantedRoof_C",                    enabled = false, size = 1.0 },
    { name = "Metal Slanted Triangular Roof",   class = "BP_BuildObject_Iron_SlopedRoofCorner_C",                enabled = false, size = 1.0 },
    { name = "Metal Slanted Corner Roof (Inverted)", class = "BP_BuildObject_Iron_SlopedRoofCornerReverse_C",         enabled = false, size = 1.0 },
    { name = "Metal Corner Roof",               class = "BP_BuildObject_Iron_TriangleStairsCorner_C",            enabled = false, size = 1.0 },
    { name = "Metal Pyramid Roof",              class = "BP_BuildObject_Iron_PyramidRoof_C",                     enabled = false, size = 1.0 },
    { name = "Metal Stairs",                    class = "BP_BuildObject_Metal_Stair_C",                          enabled = false, size = 1.0 },
    { name = "Metal Pal Passage Entrance",      class = "BP_BuildObject_Iron_WallGate_C",                        enabled = false, size = 1.0 },
    { name = "Metal Fence",                     class = "BP_BuildObject_Iron_Fence_C",                           enabled = false, size = 1.0 },
    { name = "Glass Foundation",                class = "BP_BuildObject_Glass_Foundation_C",                     enabled = false, size = 1.0 },
    { name = "Glass Triangular Foundation",     class = "BP_BuildObject_Glass_TriangleFoundation_C",             enabled = false, size = 1.0 },
    { name = "Glass Wall",                      class = "BP_BuildObject_Glass_Wall_C",                           enabled = false, size = 1.0 },
    { name = "Glass Wall and Window",           class = "BP_BuildObject_Glass_WindowWall_C",                     enabled = false, size = 1.0 },
    { name = "Glass Wall and Door",             class = "BP_BuildObject_Glass_DoorWall_C",                       enabled = false, size = 1.0 },
    { name = "Glass Diagonal Wall",             class = "BP_BuildObject_Glass_DiagonalWall_C",                   enabled = false, size = 1.0 },
    { name = "Glass Triangular Wall",           class = "BP_BuildObject_Glass_TriangleWall_C",                   enabled = false, size = 1.0 },
    { name = "Glass Triangular Wall (Inverted)", class = "BP_BuildObject_Glass_TriangleWallReverse_C",            enabled = false, size = 1.0 },
    { name = "Glass Roof",                      class = "BP_BuildObject_Glass_Roof_C",                           enabled = false, size = 1.0 },
    { name = "Glass Triangular Roof",           class = "BP_BuildObject_Glass_TriangleRoof_C",                   enabled = false, size = 1.0 },
    { name = "Glass Slanted Roof",              class = "BP_BuildObject_Glass_SlantedRoof_C",                    enabled = false, size = 1.0 },
    { name = "Glass Slanted Triangular Roof",   class = "BP_BuildObject_Glass_SlopedRoofCorner_C",               enabled = false, size = 1.0 },
    { name = "Glass Slanted Corner Roof (Inverted)", class = "BP_BuildObject_Glass_SlopedRoofCornerReverse_C",        enabled = false, size = 1.0 },
    { name = "Glass Corner Roof",               class = "BP_BuildObject_Glass_TriangleStairsCorner_C",           enabled = false, size = 1.0 },
    { name = "Glass Pyramid Roof",              class = "BP_BuildObject_Glass_PyramidRoof_C",                    enabled = false, size = 1.0 },
    { name = "Glass Stairs",                    class = "BP_BuildObject_Glass_Stair_C",                          enabled = false, size = 1.0 },
    { name = "Glass Pal Passage Entrance",      class = "BP_BuildObject_Glass_WallGate_C",                       enabled = false, size = 1.0 },
    { name = "Glass Fence",                     class = "BP_BuildObject_Glass_Fence_C",                          enabled = false, size = 1.0 },
    { name = "Japanese-Style Foundation",       class = "BP_BuildObject_JapaneseStyle_foundation_C",             enabled = false, size = 1.0 },
    { name = "Japanese-Style Triangular Foundation", class = "BP_BuildObject_JapaneseStyle_TriangleFoundation_C",     enabled = false, size = 1.0 },
    { name = "Japanese-Style Wall",             class = "BP_BuildObject_JapaneseStyle_Wall_01_C",                enabled = false, size = 1.0 },
    { name = "Japanese-Style Wall and Window",  class = "BP_BuildObject_JapaneseStyle_WindowWall_C",             enabled = false, size = 1.0 },
    { name = "Japanese-Style Door A",           class = "BP_BuildObject_JapaneseStyle_DoorWall_01_C",            enabled = false, size = 1.0 },
    { name = "Japanese-Style Door B",           class = "BP_BuildObject_JapaneseStyle_DoorWall_02_C",            enabled = false, size = 1.0 },
    { name = "Japanese-Style Door C",           class = "BP_BuildObject_JapaneseStyle_DoorWall_03_C",            enabled = false, size = 1.0 },
    { name = "Japanese-Style Diagonal Wall",    class = "BP_BuildObject_JapaneseStyle_DiagonalWall_C",           enabled = false, size = 1.0 },
    { name = "Japanese-Style Triangular Wall",  class = "BP_BuildObject_JapaneseStyle_TriangleWall_C",           enabled = false, size = 1.0 },
    { name = "Japanese-Style Triangular Wall (Inverted)", class = "BP_BuildObject_JapaneseStyle_TriangleWallReverse_C",    enabled = false, size = 1.0 },
    { name = "Japanese-Style Roof A",           class = "BP_BuildObject_JapaneseStyle_roof_01_C",                enabled = false, size = 1.0 },
    { name = "Japanese-Style Roof B",           class = "BP_BuildObject_JapaneseStyle_roof_02_C",                enabled = false, size = 1.0 },
    { name = "Japanese-Style Triangular Roof A", class = "BP_BuildObject_JapaneseStyle_TriangleRoof_01_C",        enabled = false, size = 1.0 },
    { name = "Japanese-Style Triangular Roof B", class = "BP_BuildObject_JapaneseStyle_TriangleRoof_02_C",        enabled = false, size = 1.0 },
    { name = "Japanese-Style Slanted Roof",     class = "BP_BuildObject_JapaneseStyle_SlantedRoof_C",            enabled = false, size = 1.0 },
    { name = "Japanese-Style Slanted Triangular Roof", class = "BP_BuildObject_JapaneseStyle_SlopedRoofCorner_C",       enabled = false, size = 1.0 },
    { name = "Japanese-Style Slanted Corner Roof (Inverted)", class = "BP_BuildObject_JapaneseStyle_SlopedRoofCornerReverse_C", enabled = false, size = 1.0 },
    { name = "Japanese-Style Corner Roof",      class = "BP_BuildObject_JapaneseStyle_TriangleStairsCorner_01_C", enabled = false, size = 1.0 },
    { name = "en Text",                         class = "BP_BuildObject_JapaneseStyle_TriangleStairsCorner_02_C", enabled = false, size = 1.0 },
    { name = "Japanese-Style Pyramid Roof",     class = "BP_BuildObject_JapaneseStyle_PyramidRoof_C",            enabled = false, size = 1.0 },
    { name = "Japanese-Style Stairs",           class = "BP_BuildObject_JapaneseStyle_stair_C",                  enabled = false, size = 1.0 },
    { name = "Japanese-Style Pillar",           class = "BP_BuildObject_JapaneseStyle_Pillar_C",                 enabled = false, size = 1.0 },
    { name = "Japanese-Style Pal Passage Entrance", class = "BP_BuildObject_JapaneseStyle_WallGate_C",               enabled = false, size = 1.0 },
    { name = "Japanese-Style Fence",            class = "BP_BuildObject_JapaneseStyle_Fence_C",                  enabled = false, size = 1.0 },
    { name = "Clean Foundation",                class = "BP_BuildObject_SF_Foundation_C",                        enabled = false, size = 1.0 },
    { name = "Clean Triangular Foundation",     class = "BP_BuildObject_SF_TriangleFoundation_C",                enabled = false, size = 1.0 },
    { name = "Clean Wall",                      class = "BP_BuildObject_SF_Wall_C",                              enabled = false, size = 1.0 },
    { name = "Clean Wall and Window",           class = "BP_BuildObject_SF_WindowWall_C",                        enabled = false, size = 1.0 },
    { name = "Clean Wall and Door",             class = "BP_BuildObject_SF_DoorWall_02_C",                       enabled = false, size = 1.0 },
    { name = "Clean Diagonal Wall",             class = "BP_BuildObject_SF_DiagonalWall_C",                      enabled = false, size = 1.0 },
    { name = "Clean Triangular Wall",           class = "BP_BuildObject_SF_TriangleWall_C",                      enabled = false, size = 1.0 },
    { name = "Clean Triangular Wall (Inverted)", class = "BP_BuildObject_SF_TriangleWallReverse_C",               enabled = false, size = 1.0 },
    { name = "Clean Roof",                      class = "BP_BuildObject_SF_Roof_C",                              enabled = false, size = 1.0 },
    { name = "Clean Triangular Roof",           class = "BP_BuildObject_SF_TriangleRoof_C",                      enabled = false, size = 1.0 },
    { name = "Clean Slanted Roof",              class = "BP_BuildObject_SF_SlantedRoof_C",                       enabled = false, size = 1.0 },
    { name = "Clean Slanted Triangular Roof",   class = "BP_BuildObject_SF_SlopedRoofCorner_C",                  enabled = false, size = 1.0 },
    { name = "Clean Slanted Corner Roof (Inverted)", class = "BP_BuildObject_SF_SlopedRoofCornerReverse_C",           enabled = false, size = 1.0 },
    { name = "Clean Corner Roof",               class = "BP_BuildObject_SF_TriangleStairsCorner_C",              enabled = false, size = 1.0 },
    { name = "Clean Pyramid Roof",              class = "BP_BuildObject_SF_PyramidRoof_C",                       enabled = false, size = 1.0 },
    { name = "Clean Stairs",                    class = "BP_BuildObject_SF_Stair_C",                             enabled = false, size = 1.0 },
    { name = "Clean Pal Passage Entrance",      class = "BP_BuildObject_SF_WallGate_C",                          enabled = false, size = 1.0 },
    { name = "Clean Fence",                     class = "BP_BuildObject_SF_Fence_C",                             enabled = false, size = 1.0 },
    { name = "Ancient Foundation",              class = "BP_BuildObject_Ancient_Foundation_C",                   enabled = false, size = 1.0 },
    { name = "Ancient Triangular Foundation",   class = "BP_BuildObject_Ancient_TriangleFoundation_C",           enabled = false, size = 1.0 },
    { name = "Ancient Wall",                    class = "BP_BuildObject_Ancient_Wall_C",                         enabled = false, size = 1.0 },
    { name = "Ancient Wall and Window",         class = "BP_BuildObject_Ancient_WindowWall_C",                   enabled = false, size = 1.0 },
    { name = "Ancient Wall and Door",           class = "BP_BuildObject_Ancient_DoorWall_C",                     enabled = false, size = 1.0 },
    { name = "Ancient Diagonal Wall",           class = "BP_BuildObject_Ancient_DiagonalWall_C",                 enabled = false, size = 1.0 },
    { name = "Ancient Triangular Wall",         class = "BP_BuildObject_Ancient_TriangleWall_C",                 enabled = false, size = 1.0 },
    { name = "Ancient Triangular Wall (Inverted)", class = "BP_BuildObject_Ancient_TriangleWallReverse_C",          enabled = false, size = 1.0 },
    { name = "Ancient Roof",                    class = "BP_BuildObject_Ancient_Roof_C",                         enabled = false, size = 1.0 },
    { name = "Ancient Triangular Roof",         class = "BP_BuildObject_Ancient_TriangleRoof_C",                 enabled = false, size = 1.0 },
    { name = "Ancient Slanted Roof",            class = "BP_BuildObject_Ancient_SlantedRoof_C",                  enabled = false, size = 1.0 },
    { name = "Ancient Slanted Triangular Roof", class = "BP_BuildObject_Ancient_SlopedRoofCorner_C",             enabled = false, size = 1.0 },
    { name = "Ancient Slanted Triangular Roof (Inverted)", class = "BP_BuildObject_Ancient_SlopedRoofCornerReverse_C",      enabled = false, size = 1.0 },
    { name = "Ancient Corner Roof",             class = "BP_BuildObject_Ancient_TriangleStairsCorner_C",         enabled = false, size = 1.0 },
    { name = "Ancient Pyramid Roof",            class = "BP_BuildObject_Ancient_PyramidRoof_C",                  enabled = false, size = 1.0 },
    { name = "Ancient Stairs",                  class = "BP_BuildObject_Ancient_Stair_C",                        enabled = false, size = 1.0 },
    { name = "Ancient Pillar",                  class = "BP_BuildObject_Ancient_Pillar_C",                       enabled = false, size = 1.0 },
    { name = "Ancient Pal Passage Entrance",    class = "BP_BuildObject_Ancient_WallGate_C",                     enabled = false, size = 1.0 },
    { name = "Ancient Fence",                   class = "BP_BuildObject_Ancient_Fence_C",                        enabled = false, size = 1.0 },

    -- ---------- STORAGE (30) ----------
    { name = "Wooden Chest",                    class = "BP_BuildObject_ItemChest_C",            enabled = false, size = 1.0 },
    { name = "Metal Chest",                     class = "BP_BuildObject_ItemChest_02_C",         enabled = false, size = 1.0 },
    { name = "Refined Metal Chest",             class = "BP_BuildObject_ItemChest_03_C",         enabled = false, size = 1.0 },
    { name = "Cooler Box",                      class = "BP_BuildObject_CoolerBox_C",            enabled = false, size = 1.0 },
    { name = "Refrigerator",                    class = "BP_BuildObject_Refrigerator_C",         enabled = false, size = 1.0 },
    { name = "Guild Chest",                     class = "BP_BuildObject_GuildChest_C",           enabled = false, size = 1.0 },
    { name = "Item Retrieval Machine",          class = "BP_BuildObject_BaseCampItemDispenser_C", enabled = false, size = 1.0 },
    { name = "Advanced Chest",                  class = "BP_BuildObject_ItemChest_04_C",         enabled = false, size = 1.0 },
    { name = "Wooden Box",                      class = "BP_BuildObject_Box_Wood_C",             enabled = false, size = 1.0 },
    { name = "Wooden Barrel",                   class = "BP_BuildObject_Barrel_Wood_C",          enabled = false, size = 1.0 },
    { name = "Wooden Shelf",                    class = "BP_BuildObject_Shelf_Wood_C",           enabled = false, size = 1.0 },
    { name = "Wooden Barrel Shelf",             class = "BP_BuildObject_Shelf_Cask_Wood_C",      enabled = false, size = 1.0 },
    { name = "Wooden Wall Shelf",               class = "BP_BuildObject_Shelf_Hang01_Wood_C",    enabled = false, size = 1.0 },
    { name = "Antique Bookshelf",               class = "BP_BuildObject_Shelf01_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Wardrobe",                class = "BP_BuildObject_Shelf02_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Chest",                   class = "BP_BuildObject_Shelf03_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Side Chest",              class = "BP_BuildObject_Shelf04_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Cabinet",                 class = "BP_BuildObject_Shelf05_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Long Cabinet",            class = "BP_BuildObject_Shelf06_Stone_C",        enabled = false, size = 1.0 },
    { name = "Large Antique Cabinet",           class = "BP_BuildObject_Shelf07_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Wall Cabinet",            class = "BP_BuildObject_Shelf01_Wall_Stone_C",   enabled = false, size = 1.0 },
    { name = "Iron Shelf",                      class = "BP_BuildObject_Shelf01_Iron_C",         enabled = false, size = 1.0 },
    { name = "Long Iron Shelf",                 class = "BP_BuildObject_Shelf02_Iron_C",         enabled = false, size = 1.0 },
    { name = "Iron Wall Shelf",                 class = "BP_BuildObject_Shelf01_Wall_Iron_C",    enabled = false, size = 1.0 },
    { name = "Orange Locker",                   class = "BP_BuildObject_Shelf03_Iron_C",         enabled = false, size = 1.0 },
    { name = "Locker",                          class = "BP_BuildObject_Shelf04_Iron_C",         enabled = false, size = 1.0 },
    { name = "Large Container",                 class = "BP_BuildObject_Container01_Iron_C",     enabled = false, size = 1.0 },
    { name = "Small Container",                 class = "BP_BuildObject_Box01_Iron_C",           enabled = false, size = 1.0 },
    { name = "Cloth Covered Container",         class = "BP_BuildObject_Box02_Iron_C",           enabled = false, size = 1.0 },
    { name = "Japanese-Style Chest",            class = "BP_BuildObject_Tansu_C",                enabled = false, size = 1.0 },

    -- ---------- FOOD (16) ----------
    { name = "Campfire",                        class = "BP_BuildObject_CampFire_C",           enabled = false, size = 1.0 },
    { name = "Cooking Pot",                     class = "BP_BuildObject_CookingStove_C",       enabled = false, size = 1.0 },
    { name = "Electric Kitchen",                class = "BP_BuildObject_ElectricKitchen_C",    enabled = false, size = 1.0 },
    { name = "Large-Scale Stone Oven",          class = "BP_BuildObject_HugeKitchen_C",        enabled = false, size = 1.0 },
    { name = "Ancient Kitchen",                 class = "BP_BuildObject_AncientCookingStove_C", enabled = false, size = 1.0 },
    { name = "Feed Box",                        class = "BP_BuildObject_PalFoodBox_C",         enabled = false, size = 1.0 },
    { name = "Cold Food Box",                   class = "BP_BuildObject_PalFoodBoxCool_C",     enabled = false, size = 1.0 },
    { name = "Berry Plantation",                class = "BP_BuildObject_FarmBlockV2_Berries_C", enabled = false, size = 1.0 },
    { name = "Wheat Plantation",                class = "BP_BuildObject_FarmBlockV2_wheet_C",  enabled = false, size = 1.0 },
    { name = "Tomato Plantation",               class = "BP_BuildObject_FarmBlockV2_tomato_C", enabled = false, size = 1.0 },
    { name = "Lettuce Plantation",              class = "BP_BuildObject_FarmBlockV2_Lettuce_C", enabled = false, size = 1.0 },
    { name = "Potato Plantation",               class = "BP_BuildObject_FarmBlockV2_Potato_C", enabled = false, size = 1.0 },
    { name = "Carrot Plantation",               class = "BP_BuildObject_FarmBlockV2_Carrot_C", enabled = false, size = 1.0 },
    { name = "Onion Plantation",                class = "BP_BuildObject_FarmBlockV2_Onion_C",  enabled = false, size = 1.0 },
    { name = "Skillfruit Orchard",              class = "BP_BuildObject_Farm_SkillFruits_C",   enabled = false, size = 1.0 },
    { name = "Ancient Farm",                    class = "BP_BuildObject_FarmBlockRecipe_C",    enabled = false, size = 1.0 },

    -- ---------- PAL (23) ----------
    { name = "Palbox",                          class = "BP_BuildObject_PalBoxV2_C",                            enabled = false, size = 1.0 },
    { name = "Global Palbox",                   class = "BP_BuildObject_GlobalPalStorage_C",                    enabled = false, size = 1.0 },
    { name = "Dimensional Pal Storage",         class = "BP_BuildObject_DimensionPalStorage_C",                 enabled = false, size = 1.0 },
    { name = "Palbox Control Device",           class = "BP_BuildObject_BaseCampWorkerExtraStation_C",          enabled = false, size = 1.0 },
    { name = "Monitoring Stand",                class = "BP_BuildObject_BaseCampWorkHard_C",                    enabled = false, size = 1.0 },
    { name = "High Quality Monitoring Stand",   class = "BP_BuildObject_BaseCampWorkHard_02_C",                 enabled = false, size = 1.0 },
    { name = "Ancient Monitoring Stand",        class = "BP_BuildObject_BaseCampWorkHard_03_C",                 enabled = false, size = 1.0 },
    { name = "Pal Labor Research Lab",          class = "BP_BuildObject_Lab_C",                                 enabled = false, size = 1.0 },
    { name = "Pal Expedition Station",          class = "BP_BuildObject_Expedition_C",                          enabled = false, size = 1.0 },   -- [MiniBuilds]
    { name = "Statue of Power",                 class = "BP_BuildObject_BuildableGoddessStatue_C",              enabled = false, size = 1.0 },
    { name = "Pal Essence Condenser",           class = "BP_BuildObject_CharacterRankUp_C",                     enabled = false, size = 1.0 },
    { name = "Pal Surgery Table",               class = "BP_BuildObject_OperatingTable_C",                      enabled = false, size = 1.0 },
    { name = "Breeding Farm",                   class = "BP_BuildObject_BreedFarm_C",                           enabled = false, size = 1.0 },   -- [MiniBuilds]
    { name = "Ranch",                           class = "BP_BuildObject_MonsterFarm_C",                         enabled = false, size = 1.0 },   -- [MiniBuilds]
    { name = "Egg Incubator",                   class = "BP_BuildObject_HatchingPalEgg_C",                      enabled = false, size = 1.0 },
    { name = "Electric Egg Incubator",          class = "BP_BuildObject_ElectricHatchingPalEgg_C",              enabled = false, size = 1.0 },
    { name = "Large Incubator",                 class = "BP_BuildObject_MultiHatchingPalEgg_C",                 enabled = false, size = 1.0 },
    { name = "Large-Scale Electric Egg Incubator", class = "BP_BuildObject_MultiElectricHatchingPalEgg_C",         enabled = false, size = 1.0 },
    { name = "Ancient Hatchery",                class = "BP_BuildObject_MultiElectricHatchingPalEggWithBreed_C", enabled = false, size = 1.0 },
    { name = "Pal Dressing Facility",           class = "BP_BuildObject_CharacterSkinChange_C",                 enabled = false, size = 1.0 },
    { name = "Viewing Cage",                    class = "BP_BuildObject_DisplayCharacter_C",                    enabled = false, size = 1.0 },
    { name = "Pal Disassembly Conveyor",        class = "BP_BuildObject_DismantlingConveyor_C",                 enabled = false, size = 1.0 },
    { name = "Summoning Altar",                 class = "BP_BuildObject_Altar_C",                               enabled = false, size = 1.0 },

    -- ---------- INFRASTRUCTURE (25) ----------
    { name = "Shoddy Bed",                      class = "BP_BuildObject_PlayerBed_02_C",                   enabled = false, size = 1.0 },
    { name = "Fine Bed",                        class = "BP_BuildObject_PlayerBed_03_C",                   enabled = false, size = 1.0 },
    { name = "Straw Pal Bed",                   class = "BP_BuildObject_MedicalPalBed_02_C",               enabled = false, size = 1.0 },
    { name = "Fluffy Pal Bed",                  class = "BP_BuildObject_MedicalPalBed_03_C",               enabled = false, size = 1.0 },
    { name = "Large Pal Bed",                   class = "BP_BuildObject_MedicalPalBed_04_C",               enabled = false, size = 1.0 },
    { name = "Pal Pod",                         class = "BP_BuildObject_MedicalPalBed_05_C",               enabled = false, size = 1.0 },
    { name = "Ancient Pal Bed",                 class = "BP_BuildObject_MedicalPalBed_06_C",               enabled = false, size = 1.0 },
    { name = "Human-Powered Generator",         class = "BP_BuildObject_EnergyGenerator_Electric_Manual_C", enabled = false, size = 1.0 },
    { name = "Power Generator",                 class = "BP_BuildObject_EnergyGenerator_Electric_C",       enabled = false, size = 1.0 },
    { name = "Large Power Generator",           class = "BP_BuildObject_EnergyGenerator_Large_C",          enabled = false, size = 1.0 },
    { name = "Ancient Power Generator",         class = "BP_BuildObject_AncientEnergyGenerator_C",         enabled = false, size = 1.0 },
    { name = "Accumulator",                     class = "BP_BuildObject_EnergyStorage_Electric_C",         enabled = false, size = 1.0 },
    { name = "Heater",                          class = "BP_BuildObject_HeaterMedieval_C",                 enabled = false, size = 1.0 },
    { name = "Cooler",                          class = "BP_BuildObject_CoolerMedieval_C",                 enabled = false, size = 1.0 },
    { name = "Electric Heater",                 class = "BP_BuildObject_HeaterElectric_C",                 enabled = false, size = 1.0 },
    { name = "Electric Cooler",                 class = "BP_BuildObject_CoolerElectric_C",                 enabled = false, size = 1.0 },
    { name = "Ancient Air Conditioner",         class = "BP_BuildObject_CoolerAncient_C",                  enabled = false, size = 1.0 },
    { name = "Hot Spring",                      class = "BP_BuildObject_Spa_C",                            enabled = false, size = 1.0 },
    { name = "High Quality Hot Spring",         class = "BP_BuildObject_Spa_2_C",                          enabled = false, size = 1.0 },
    { name = "Japanese-Style Hot Spring",       class = "BP_BuildObject_Spa_3_C",                          enabled = false, size = 1.0 },
    { name = "Ancient Hot Spring",              class = "BP_BuildObject_Spa_4_C",                          enabled = false, size = 1.0 },
    { name = "Clinic",                          class = "BP_BuildObject_Clinic_C",                         enabled = false, size = 1.0 },
    { name = "Ancient Clinic",                  class = "BP_BuildObject_Clinic_02_C",                      enabled = false, size = 1.0 },
    { name = "Medicine Rack",                   class = "BP_BuildObject_PalMedicineBox_C",                 enabled = false, size = 1.0 },
    { name = "Great Eagle Statue",              class = "BP_BuildObject_FastTravelPoint_C",                enabled = false, size = 1.0 },

    -- ---------- FURNITURE (159) ----------
    { name = "Square Table",                    class = "BP_BuildObject_TableSquare_Wood_C",        enabled = false, size = 1.0 },
    { name = "Tidy Square Table",               class = "BP_BuildObject_TableSquare_Wood_None_C",   enabled = false, size = 1.0 },
    { name = "Round Table",                     class = "BP_BuildObject_TableCircular_Wood_C",      enabled = false, size = 1.0 },
    { name = "Tidy Round Table",                class = "BP_BuildObject_TableCircular_Wood_None_C", enabled = false, size = 1.0 },
    { name = "Wooden Counter",                  class = "BP_BuildObject_Counter_Wood_C",            enabled = false, size = 1.0 },
    { name = "Antique Desk",                    class = "BP_BuildObject_Desk01_Stone_C",            enabled = false, size = 1.0 },
    { name = "Antique Round Table",             class = "BP_BuildObject_TableCircular01_Stone_C",   enabled = false, size = 1.0 },
    { name = "Round Iron Table",                class = "BP_BuildObject_TableCircular01_Iron_C",    enabled = false, size = 1.0 },
    { name = "Iron Desk",                       class = "BP_BuildObject_Desk01_Iron_C",             enabled = false, size = 1.0 },
    { name = "Ironwood Side Table",             class = "BP_BuildObject_TableSide01_Iron_C",        enabled = false, size = 1.0 },
    { name = "Ironwood Table",                  class = "BP_BuildObject_TableSquare01_Iron_C",      enabled = false, size = 1.0 },
    { name = "Ironwood Low Table",              class = "BP_BuildObject_TableSquare02_Iron_C",      enabled = false, size = 1.0 },
    { name = "Japanese Writing Table",          class = "BP_BuildObject_Fudukue_C",                 enabled = false, size = 1.0 },
    { name = "Laboratory Desk",                 class = "BP_BuildObject_SF_Desk_C",                 enabled = false, size = 1.0 },
    { name = "Wooden Bench",                    class = "BP_BuildObject_Bench_Wood_C",              enabled = false, size = 1.0 },
    { name = "Wooden Stool",                    class = "BP_BuildObject_Stool_Wood_C",              enabled = false, size = 1.0 },
    { name = "Wooden Bar Stool",                class = "BP_BuildObject_Stool_High_Wood_C",         enabled = false, size = 1.0 },
    { name = "Wooden Chair",                    class = "BP_BuildObject_Chair01_Wood_C",            enabled = false, size = 1.0 },
    { name = "Antique Wooden Chair",            class = "BP_BuildObject_Chair01_Stone_C",           enabled = false, size = 1.0 },
    { name = "Antique Green Wooden Chair",      class = "BP_BuildObject_Chair02_Stone_C",           enabled = false, size = 1.0 },
    { name = "Antique Stool",                   class = "BP_BuildObject_Stool01_Stone_C",           enabled = false, size = 1.0 },
    { name = "Antique Armchair",                class = "BP_BuildObject_Sofa01_Stone_C",            enabled = false, size = 1.0 },
    { name = "Antique Couch",                   class = "BP_BuildObject_Sofa02_Stone_C",            enabled = false, size = 1.0 },
    { name = "Antique Ottoman",                 class = "BP_BuildObject_Sofa03_Stone_C",            enabled = false, size = 1.0 },
    { name = "Iron Stool",                      class = "BP_BuildObject_Stool01_Iron_C",            enabled = false, size = 1.0 },
    { name = "Iron Chair",                      class = "BP_BuildObject_Chair02_Iron_C",            enabled = false, size = 1.0 },
    { name = "Leather Chair",                   class = "BP_BuildObject_Chair01_Iron_C",            enabled = false, size = 1.0 },
    { name = "Leather Armchair",                class = "BP_BuildObject_Sofa01_Iron_C",             enabled = false, size = 1.0 },
    { name = "Leather Couch",                   class = "BP_BuildObject_Sofa02_Iron_C",             enabled = false, size = 1.0 },
    { name = "Frog Chair",                      class = "BP_BuildObject_Chair01_Pal_C",             enabled = false, size = 1.0 },
    { name = "Japanese Floor Chair",            class = "BP_BuildObject_Zaisu_C",                   enabled = false, size = 1.0 },
    { name = "Japanese Floor Cushion",          class = "BP_BuildObject_Zabuton_C",                 enabled = false, size = 1.0 },
    { name = "Laboratory Chair",                class = "BP_BuildObject_SF_Chair_C",                enabled = false, size = 1.0 },
    { name = "Antique Carpet",                  class = "BP_BuildObject_Rug01_Stone_C",             enabled = false, size = 1.0 },
    { name = "Antique Red Carpet",              class = "BP_BuildObject_Rug02_Stone_C",             enabled = false, size = 1.0 },
    { name = "Antique Green Carpet",            class = "BP_BuildObject_Rug03_Stone_C",             enabled = false, size = 1.0 },
    { name = "Antique Long Carpet",             class = "BP_BuildObject_Rug04_Stone_C",             enabled = false, size = 1.0 },
    { name = "Fur rug",                         class = "BP_BuildObject_Rug_Wood_C",                enabled = false, size = 1.0 },
    { name = "Wooden Decorative Wall Shelf",    class = "BP_BuildObject_Shelf_Hang02_Wood_C",       enabled = false, size = 1.0 },
    { name = "Antique Wall Mirror",             class = "BP_BuildObject_Mirror01_Wall_Stone_C",     enabled = false, size = 1.0 },
    { name = "Antique Curtain",                 class = "BP_BuildObject_Curtain01_Wall_Stone_C",    enabled = false, size = 1.0 },
    { name = "Wall Clock",                      class = "BP_BuildObject_Clock01_Wall_Iron_C",       enabled = false, size = 1.0 },
    { name = "Small Wall Ivy",                  class = "BP_BuildObject_Ivy02_C",                   enabled = false, size = 1.0 },
    { name = "Big Wall Ivy",                    class = "BP_BuildObject_Ivy01_C",                   enabled = false, size = 1.0 },
    { name = "Horizontal Wall Ivy",             class = "BP_BuildObject_Ivy03_C",                   enabled = false, size = 1.0 },
    { name = "Emergency Exit Wall Sign",        class = "BP_BuildObject_SignExit_Wall_Iron_C",      enabled = false, size = 1.0 },
    { name = "Emergency Exit Ceiling Sign",     class = "BP_BuildObject_SignExit_Ceiling_Iron_C",   enabled = false, size = 1.0 },
    { name = "Hanging Scroll",                  class = "BP_BuildObject_Kakejiku_C",                enabled = false, size = 1.0 },
    { name = "Houseplant",                      class = "BP_BuildObject_Plant01_Plant_C",           enabled = false, size = 1.0 },
    { name = "Houseplant and Chair",            class = "BP_BuildObject_Plant02_Plant_C",           enabled = false, size = 1.0 },
    { name = "Tabletop Houseplant",             class = "BP_BuildObject_Plant03_Plant_C",           enabled = false, size = 1.0 },
    { name = "Potted Houseplant",               class = "BP_BuildObject_Plant04_Plant_C",           enabled = false, size = 1.0 },
    { name = "Bonsai",                          class = "BP_BuildObject_Bonsai_C",                  enabled = false, size = 1.0 },
    { name = "Flower Arrangement",              class = "BP_BuildObject_Seika_C",                   enabled = false, size = 1.0 },
    { name = "Faux Greenery A",                 class = "BP_BuildObject_FurnitureTree01_Green_C",   enabled = false, size = 1.0 },
    { name = "Faux Greenery B",                 class = "BP_BuildObject_FurnitureTree02_Green_C",   enabled = false, size = 1.0 },
    { name = "Faux Greenery C",                 class = "BP_BuildObject_FurnitureTree03_Green_C",   enabled = false, size = 1.0 },
    { name = "Faux Crimson Foliage A",          class = "BP_BuildObject_FurnitureTree01_Red_C",     enabled = false, size = 1.0 },
    { name = "Faux Crimson Foliage B",          class = "BP_BuildObject_FurnitureTree02_Red_C",     enabled = false, size = 1.0 },
    { name = "Faux Crimson Foliage C",          class = "BP_BuildObject_FurnitureTree03_Red_C",     enabled = false, size = 1.0 },
    { name = "Faux Golden Foliage A",           class = "BP_BuildObject_FurnitureTree01_Yellow_C",  enabled = false, size = 1.0 },
    { name = "Faux Golden Foliage B",           class = "BP_BuildObject_FurnitureTree02_Yellow_C",  enabled = false, size = 1.0 },
    { name = "Faux Golden Foliage C",           class = "BP_BuildObject_FurnitureTree03_Yellow_C",  enabled = false, size = 1.0 },
    { name = "Faux Cherry Blossoms A",          class = "BP_BuildObject_FurnitureTree01_Cherry_C",  enabled = false, size = 1.0 },
    { name = "Faux Cherry Blossoms B",          class = "BP_BuildObject_FurnitureTree02_Cherry_C",  enabled = false, size = 1.0 },
    { name = "Faux Cherry Blossoms C",          class = "BP_BuildObject_FurnitureTree03_Cherry_C",  enabled = false, size = 1.0 },
    { name = "Faux Tropical Greenery A",        class = "BP_BuildObject_FurnitureTree01_Tropical_C", enabled = false, size = 1.0 },
    { name = "Faux Tropical Greenery B",        class = "BP_BuildObject_FurnitureTree02_Tropical_C", enabled = false, size = 1.0 },
    { name = "Faux Tropical Greenery C",        class = "BP_BuildObject_FurnitureTree03_Tropical_C", enabled = false, size = 1.0 },
    { name = "Faux Snowy Greenery A",           class = "BP_BuildObject_FurnitureTree01_Snow_C",    enabled = false, size = 1.0 },
    { name = "Faux Snowy Greenery B",           class = "BP_BuildObject_FurnitureTree02_Snow_C",    enabled = false, size = 1.0 },
    { name = "Faux Snowy Greenery C",           class = "BP_BuildObject_FurnitureTree03_Snow_C",    enabled = false, size = 1.0 },
    { name = "Faux Desert Greenery A",          class = "BP_BuildObject_FurnitureTree01_Desert_C",  enabled = false, size = 1.0 },
    { name = "Faux Desert Greenery B",          class = "BP_BuildObject_FurnitureTree02_Desert_C",  enabled = false, size = 1.0 },
    { name = "Faux Desert Greenery C",          class = "BP_BuildObject_FurnitureTree03_Desert_C",  enabled = false, size = 1.0 },
    { name = "Faux Bamboo A",                   class = "BP_BuildObject_FurnitureTree01_Bamboo_C",  enabled = false, size = 1.0 },
    { name = "Faux Bamboo B",                   class = "BP_BuildObject_FurnitureTree02_Bamboo_C",  enabled = false, size = 1.0 },
    { name = "Faux Bamboo C",                   class = "BP_BuildObject_FurnitureTree03_Bamboo_C",  enabled = false, size = 1.0 },
    { name = "Faux Bush",                       class = "BP_BuildObject_FurnitureBush01_Green_C",   enabled = false, size = 1.0 },
    { name = "Faux Golden Bush",                class = "BP_BuildObject_FurnitureBush01_Yellow_C",  enabled = false, size = 1.0 },
    { name = "Antique Dresser",                 class = "BP_BuildObject_TableDresser01_Stone_C",    enabled = false, size = 1.0 },
    { name = "Faux Flowering Bush A",           class = "BP_BuildObject_FurnitureBush01_Flower_C",  enabled = false, size = 1.0 },
    { name = "Antique Bathtub",                 class = "BP_BuildObject_BathTub_Stone_C",           enabled = false, size = 1.0 },
    { name = "Faux Flowering Bush B",           class = "BP_BuildObject_FurnitureBush02_Flower_C",  enabled = false, size = 1.0 },
    { name = "Antique Braided Basket",          class = "BP_BuildObject_Box01_Stone_C",             enabled = false, size = 1.0 },
    { name = "Faux Tropical Bush",              class = "BP_BuildObject_FurnitureBush01_Tropical_C", enabled = false, size = 1.0 },
    { name = "Antique Partition",               class = "BP_BuildObject_Partition_Stone_C",         enabled = false, size = 1.0 },
    { name = "Faux White Bush",                 class = "BP_BuildObject_FurnitureBush01_Snow_C",    enabled = false, size = 1.0 },
    { name = "Antique Towel Rack",              class = "BP_BuildObject_TowlRack01_Stone_C",        enabled = false, size = 1.0 },
    { name = "Antique Oval Mirror",             class = "BP_BuildObject_Mirror01_Stone_C",          enabled = false, size = 1.0 },
    { name = "Antique Mirror",                  class = "BP_BuildObject_Mirror02_Stone_C",          enabled = false, size = 1.0 },
    { name = "Grand Piano",                     class = "BP_BuildObject_Piano01_Stone_C",           enabled = false, size = 1.0 },
    { name = "Upright Piano",                   class = "BP_BuildObject_Piano02_Stone_C",           enabled = false, size = 1.0 },
    { name = "Antique Washstand",               class = "BP_BuildObject_TableSink01_Stone_C",       enabled = false, size = 1.0 },
    { name = "Antique Toilet",                  class = "BP_BuildObject_Toilet01_Stone_C",          enabled = false, size = 1.0 },
    { name = "Antique Toilet Paper Holder",     class = "BP_BuildObject_ToiletHolder01_Stone_C",    enabled = false, size = 1.0 },
    { name = "Antique Globe",                   class = "BP_BuildObject_Globe01_Stone_C",           enabled = false, size = 1.0 },
    { name = "Antique Stove",                   class = "BP_BuildObject_Stove01_Stone_C",           enabled = false, size = 1.0 },
    { name = "Antique Grandfather Clock",       class = "BP_BuildObject_Clock01_Stone_C",           enabled = false, size = 1.0 },
    { name = "Cable Reel",                      class = "BP_BuildObject_CableCoil01_Iron_C",        enabled = false, size = 1.0 },
    { name = "Garbage Bag",                     class = "BP_BuildObject_GarbageBag_Iron_C",         enabled = false, size = 1.0 },
    { name = "Earthen Pipe",                    class = "BP_BuildObject_PipeClay01_Iron_C",         enabled = false, size = 1.0 },
    { name = "Tire",                            class = "BP_BuildObject_Tire01_Iron_C",             enabled = false, size = 1.0 },
    { name = "Red Metal Barrel",                class = "BP_BuildObject_Barrel01_Iron_C",           enabled = false, size = 1.0 },
    { name = "Blue Metal Barrel",               class = "BP_BuildObject_Barrel02_Iron_C",           enabled = false, size = 1.0 },
    { name = "Green Metal Barrel",              class = "BP_BuildObject_Barrel03_Iron_C",           enabled = false, size = 1.0 },
    { name = "Soccer Goal",                     class = "BP_BuildObject_GoalSoccer_Iron_C",         enabled = false, size = 1.0 },
    { name = "Claw Machine",                    class = "BP_BuildObject_MachineGame01_Iron_C",      enabled = false, size = 1.0 },
    { name = "Arcade Game Cabinet",             class = "BP_BuildObject_ArcadeVideoGame_C",         enabled = false, size = 1.0 },
    { name = "Cola Vending Machine",            class = "BP_BuildObject_MachineVending01_Iron_C",   enabled = false, size = 1.0 },
    { name = "Old TV",                          class = "BP_BuildObject_Television01_Iron_C",       enabled = false, size = 1.0 },
    { name = "Traffic Cone",                    class = "BP_BuildObject_TrafficCone01_Iron_C",      enabled = false, size = 1.0 },
    { name = "Fat Traffic Cone",                class = "BP_BuildObject_TrafficCone02_Iron_C",      enabled = false, size = 1.0 },
    { name = "Skinny Traffic Cone",             class = "BP_BuildObject_TrafficCone03_Iron_C",      enabled = false, size = 1.0 },
    { name = "Traffic Light",                   class = "BP_BuildObject_TrafficLight01_Iron_C",     enabled = false, size = 1.0 },
    { name = "No Pals Beyond Sign",             class = "BP_BuildObject_TrafficSign01_Iron_C",      enabled = false, size = 1.0 },
    { name = "Stop Sign",                       class = "BP_BuildObject_TrafficSign02_Iron_C",      enabled = false, size = 1.0 },
    { name = "Beware of Eikthyrdeer Sign",      class = "BP_BuildObject_TrafficSign03_Iron_C",      enabled = false, size = 1.0 },
    { name = "Beware of Mammorest Sign",        class = "BP_BuildObject_TrafficSign04_Iron_C",      enabled = false, size = 1.0 },
    { name = "Barricade",                       class = "BP_BuildObject_TrafficBarricade01_Iron_C", enabled = false, size = 1.0 },
    { name = "Orange Barricade",                class = "BP_BuildObject_TrafficBarricade02_Iron_C", enabled = false, size = 1.0 },
    { name = "Red Iron Barricade",              class = "BP_BuildObject_TrafficBarricade03_Iron_C", enabled = false, size = 1.0 },
    { name = "White Iron Barricade",            class = "BP_BuildObject_TrafficBarricade04_Iron_C", enabled = false, size = 1.0 },
    { name = "Iron Fence",                      class = "BP_BuildObject_TrafficBarricade05_Iron_C", enabled = false, size = 1.0 },
    { name = "Wire Fence",                      class = "BP_BuildObject_Wire_Fence_C",              enabled = false, size = 1.0 },
    { name = "Wooden Barricade",                class = "BP_BuildObject_WoodenBarricade_C",         enabled = false, size = 1.0 },
    { name = "Folding Screen",                  class = "BP_BuildObject_Byobu_C",                   enabled = false, size = 1.0 },
    { name = "Japanese Hearth",                 class = "BP_BuildObject_Irori_C",                   enabled = false, size = 1.0 },
    { name = "Stone Lantern",                   class = "BP_BuildObject_Toro_C",                    enabled = false, size = 1.0 },
    { name = "Deer Scare",                      class = "BP_BuildObject_Shishiodoshi_C",            enabled = false, size = 1.0 },
    { name = "Incense Burner",                  class = "BP_BuildObject_Koro_C",                    enabled = false, size = 1.0 },
    { name = "Faux Rock",                       class = "BP_BuildObject_FurnitureStone01_C",        enabled = false, size = 1.0 },
    { name = "Jetragon Statue",                 class = "BP_BuildObject_JetDragonStatue_C",         enabled = false, size = 1.0 },
    { name = "Frostallion Statue",              class = "BP_BuildObject_IceHorseStatue_C",          enabled = false, size = 1.0 },
    { name = "Yakumo Statue",                   class = "BP_BuildObject_GuardianDogStatue_C",       enabled = false, size = 1.0 },
    { name = "Lyleen Statue",                   class = "BP_BuildObject_LilyQueenStatue_C",         enabled = false, size = 1.0 },
    { name = "Moon Lord Statue",                class = "BP_BuildObject_YakushimaBoss002_Relic_C",  enabled = false, size = 1.0 },
    { name = "Rayne Syndicate Standard",        class = "BP_BuildObject_Hunter_Flag_C",             enabled = false, size = 1.0 },
    { name = "Rayne Syndicate Vertical Banner", class = "BP_BuildObject_Hunter_Banner_C",           enabled = false, size = 1.0 },
    { name = "Rayne Syndicate Flag",            class = "BP_BuildObject_Hunter_GangFlag_C",         enabled = false, size = 1.0 },
    { name = "Free Pal Alliance Standard",      class = "BP_BuildObject_Believer_Flag_C",           enabled = false, size = 1.0 },
    { name = "Free Pal Alliance Vertical Banner", class = "BP_BuildObject_Believer_Banner_C",         enabled = false, size = 1.0 },
    { name = "Free Pal Alliance Flag",          class = "BP_BuildObject_ConservationGroupBannerA_C", enabled = false, size = 1.0 },
    { name = "Free Pal Alliance Horizontal Banner", class = "BP_BuildObject_ConservationGroupBannerB_C", enabled = false, size = 1.0 },
    { name = "Brothers of the Eternal Pyre Standard", class = "BP_BuildObject_FireCult_Flag_C",           enabled = false, size = 1.0 },
    { name = "Brothers of the Eternal Pyre Vertical Banner", class = "BP_BuildObject_FireCult_Banner_C",         enabled = false, size = 1.0 },
    { name = "PIDF Standard",                   class = "BP_BuildObject_Police_Flag_C",             enabled = false, size = 1.0 },
    { name = "PIDF Vertical Banner",            class = "BP_BuildObject_Police_Banner_C",           enabled = false, size = 1.0 },
    { name = "PAL Genetic Research Unit Standard", class = "BP_BuildObject_Scientist_Flag_C",          enabled = false, size = 1.0 },
    { name = "PAL Genetic Research Unit Vertical Banner", class = "BP_BuildObject_Scientist_Banner_C",        enabled = false, size = 1.0 },
    { name = "Moonflower Standard",             class = "BP_BuildObject_Ninja_Flag_C",              enabled = false, size = 1.0 },
    { name = "Moonflower Vertical Banner",      class = "BP_BuildObject_Ninja_Banner_C",            enabled = false, size = 1.0 },
    { name = "Feybreak Flag",                   class = "BP_BuildObject_DarkIsland_Flag_C",         enabled = false, size = 1.0 },
    { name = "Feybreak Banner",                 class = "BP_BuildObject_DarkIsland_Banner_C",       enabled = false, size = 1.0 },
    { name = "Azure Covenant Flag",             class = "BP_BuildObject_SkyIsland_Flag_C",          enabled = false, size = 1.0 },
    { name = "Azure Covenant Banner",           class = "BP_BuildObject_SkyIsland_Banner_C",        enabled = false, size = 1.0 },
    { name = "Banyan_Big",                      class = "BP_BuildObject_Banyan_Big_C",              enabled = false, size = 1.0 },
    { name = "Tuppanyan sticker",               class = "BP_BuildObject_Decal_PalSticker_PinkCat_C", enabled = false, size = 1.0 },
    { name = "Aerial Cage",                     class = "BP_BuildObject_PalCage_C",                 enabled = false, size = 1.0 },

    -- ---------- LIGHT (22) ----------
    { name = "Mounted Torch",                   class = "BP_BuildObject_TorchStand_C",             enabled = false, size = 1.0 },
    { name = "Lamp",                            class = "BP_BuildObject_LampStand_C",              enabled = false, size = 1.0 },
    { name = "Large Mounted Lamp",              class = "BP_BuildObject_LampStandLarge_C",         enabled = false, size = 1.0 },
    { name = "Brick Fireplace",                 class = "BP_BuildObject_Light_FirePlace01_C",      enabled = false, size = 1.0 },
    { name = "Fireplace",                       class = "BP_BuildObject_Light_FirePlace02_C",      enabled = false, size = 1.0 },
    { name = "Simple Street Lamp",              class = "BP_BuildObject_Light_LightPole01_C",      enabled = false, size = 1.0 },
    { name = "Double Street Lamp",              class = "BP_BuildObject_Light_LightPole02_C",      enabled = false, size = 1.0 },
    { name = "Retro Street Lamp",               class = "BP_BuildObject_Light_LightPole03_C",      enabled = false, size = 1.0 },
    { name = "Stylish Street Lamp",             class = "BP_BuildObject_Light_LightPole04_C",      enabled = false, size = 1.0 },
    { name = "Antique Brown Floor Lamp",        class = "BP_BuildObject_Light_FloorLamp01_C",      enabled = false, size = 1.0 },
    { name = "Antique Red Floor Lamp",          class = "BP_BuildObject_Light_FloorLamp02_C",      enabled = false, size = 1.0 },
    { name = "Japanese Paper Lantern",          class = "BP_BuildObject_Andon_C",                  enabled = false, size = 1.0 },
    { name = "Red Wooden Lantern",              class = "BP_BuildObject_Light_Shrine_Lantern_C",   enabled = false, size = 1.0 },
    { name = "Majestic Candlestick",            class = "BP_BuildObject_CandleStand_C",            enabled = false, size = 1.0 },
    { name = "Ceremonial Candlestick",          class = "BP_BuildObject_FireStand_C",              enabled = false, size = 1.0 },
    { name = "Wall Torch",                      class = "BP_BuildObject_TorchHang_C",              enabled = false, size = 1.0 },
    { name = "Wall Lamp",                       class = "BP_BuildObject_Light_CandleSticks_Wall_C", enabled = false, size = 1.0 },
    { name = "Majestic Wall Torch",             class = "BP_BuildObject_TorchHang02_C",            enabled = false, size = 1.0 },
    { name = "Ceiling Lamp",                    class = "BP_BuildObject_LampTop_C",                enabled = false, size = 1.0 },
    { name = "Large Ceiling Lamp",              class = "BP_BuildObject_LampTopLarge_C",           enabled = false, size = 1.0 },
    { name = "Chandelier",                      class = "BP_BuildObject_Light_CandleSticks_Top_C", enabled = false, size = 1.0 },
    { name = "Paper Lantern",                   class = "BP_BuildObject_LanternTop_C",             enabled = false, size = 1.0 },

    -- ---------- DEFENSE (19) ----------
    { name = "Hanging Trap",                    class = "BP_BuildObject_Trap_Noose_C",                                enabled = false, size = 1.0 },
    { name = "Bear Trap (Small)",               class = "BP_BuildObject_Trap_LegHold_C",                              enabled = false, size = 1.0 },
    { name = "Bear Trap (Large)",               class = "BP_BuildObject_Trap_LegHold_Big_C",                          enabled = false, size = 1.0 },
    { name = "Mine",                            class = "BP_BuildObject_Trap_MineAttack_C",                           enabled = false, size = 1.0 },
    { name = "Electric Mine",                   class = "BP_BuildObject_Trap_MineElecShock_C",                        enabled = false, size = 1.0 },
    { name = "Ice Mine",                        class = "BP_BuildObject_Trap_MineFreeze_C",                           enabled = false, size = 1.0 },
    { name = "Sandbag",                         class = "BP_BuildObject_DefenseWait_C",                               enabled = false, size = 1.0 },
    { name = "Mounted Crossbow",                class = "BP_BuildObjectDefenseBulletLauncher_BowGun_C",               enabled = false, size = 1.0 },
    { name = "Mounted Machine Gun",             class = "BP_BuildObjectDefenseBulletLauncher_Machinegun_C",           enabled = false, size = 1.0 },
    { name = "Mounted Missile Launcher",        class = "BP_BuildObjectDefenseBulletLauncher_Missile_C",              enabled = false, size = 1.0 },
    { name = "Ancient Turret",                  class = "BP_BuildObjectDefenseBulletLauncher_Machinegun_AutoTurret_C", enabled = false, size = 1.0 },
    { name = "Alarm Bell",                      class = "BP_BuildObject_BaseCampBattleDirector_C",                    enabled = false, size = 1.0 },
    { name = "Moving Panels",                   class = "BP_BuildObject_Trap_MovingPanel_C",                          enabled = false, size = 1.0 },
    { name = "Wooden Defensive Wall",           class = "BP_BuildObject_DefenseWall_Wood_C",                          enabled = false, size = 1.0 },
    { name = "Stone Defensive Wall",            class = "BP_BuildObject_DefenseWall_C",                               enabled = false, size = 1.0 },
    { name = "Metal Defensive Wall",            class = "BP_BuildObject_DefenseWall_Metal_C",                         enabled = false, size = 1.0 },
    { name = "Wooden Gate",                     class = "BP_BuildObject_Wood_Gate_C",                                 enabled = false, size = 1.0 },
    { name = "Stone Gate",                      class = "BP_BuildObject_Stone_Gate_C",                                enabled = false, size = 1.0 },
    { name = "Iron Gate",                       class = "BP_BuildObject_Metal_Gate_C",                                enabled = false, size = 1.0 },

    -- ---------- OTHER (20) ----------
    { name = "Water Fountain",                  class = "BP_BuildObject_Fountain_C",          enabled = false, size = 1.0 },
    { name = "Flower Bed",                      class = "BP_BuildObject_FlowerBed_C",         enabled = false, size = 1.0 },
    { name = "Silo",                            class = "BP_BuildObject_Silo_C",              enabled = false, size = 1.0 },
    { name = "Stump and Axe",                   class = "BP_BuildObject_Stump_C",             enabled = false, size = 1.0 },
    { name = "Mining Cart",                     class = "BP_BuildObject_MiningTool_C",        enabled = false, size = 1.0 },
    { name = "Witch Cauldron",                  class = "BP_BuildObject_Cauldron_C",          enabled = false, size = 1.0 },
    { name = "Snowman",                         class = "BP_BuildObject_Snowman_C",           enabled = false, size = 1.0 },
    { name = "Electric Pylon",                  class = "BP_BuildObject_TransmissionTower_C", enabled = false, size = 1.0 },
    { name = "Large Toolbox",                   class = "BP_BuildObject_ToolBoxV1_C",         enabled = false, size = 1.0 },
    { name = "Flame Cauldron",                  class = "BP_BuildObject_OlympicCauldron_C",   enabled = false, size = 1.0 },
    { name = "Alpha Wave Generator",            class = "BP_BuildObject_SanityDecrease1_C",   enabled = false, size = 1.0 },
    { name = "Beta Wave Generator",             class = "BP_BuildObject_WorkSpeedIncrease1_C", enabled = false, size = 1.0 },
    { name = "Flea Market (Pals)",              class = "BP_BuildObject_PalBooth_C",          enabled = false, size = 1.0 },
    { name = "Flea Market (Items)",             class = "BP_BuildObject_ItemBooth_C",         enabled = false, size = 1.0 },
    { name = "Training Dummy",                  class = "BP_BuildObject_DamagedScarecrow_C",  enabled = false, size = 1.0 },
    { name = "Sign",                            class = "BP_BuildObject_Signboard_C",         enabled = false, size = 1.0 },
    { name = "Wall-Mounted Sign",               class = "BP_BuildObject_WallSignboard_C",     enabled = false, size = 1.0 },
    { name = "Tombstone",                       class = "BP_BuildObject_Headstone_C",         enabled = false, size = 1.0 },
    { name = "en Text",                         class = "BP_BuildObject_WoodCreator_C",       enabled = false, size = 1.0 },
    { name = "DamagedScarecrow_Test",           class = "BP_BuildObject_DamagedScarecrow_2_C", enabled = false, size = 1.0 },
}
